Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData",
            "name": "AfmData",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#method_getWidth"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024ascender",
            "name": "ascender",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_ascender"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024descender",
            "name": "descender",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_descender"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_capHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024xHeight",
            "name": "xHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_xHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_italicAngle"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024stemV",
            "name": "stemV",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_stemV"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024missingWidth",
            "name": "missingWidth",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_missingWidth"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024fontBBox",
            "name": "fontBBox",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_fontBBox"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\AfmData\u003A\u003A\u0024widths",
            "name": "widths",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-AfmData.html#property_widths"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\StandardFontMetrics",
            "name": "StandardFontMetrics",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-StandardFontMetrics.html"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics\\StandardFontMetrics\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Phpdftk-FontMetrics-StandardFontMetrics.html#method_get"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\FontMetrics",
            "name": "FontMetrics",
            "summary": "",
            "url": "namespaces/phpdftk-fontmetrics.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
