Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Filters\\Ascii85Filter",
            "name": "Ascii85Filter",
            "summary": "ASCII85Decode\u0020\u2014\u0020base\u002D85\u0020encoding\u0020for\u0020binary\u0020data\u0020\u0028ISO\u002032000\u002D2\u0020\u00A77.4.3\u0029.",
            "url": "classes/Phpdftk-Filters-Ascii85Filter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\Ascii85Filter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-Ascii85Filter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\Ascii85Filter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-Ascii85Filter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\AsciiHexFilter",
            "name": "AsciiHexFilter",
            "summary": "ASCIIHexDecode\u0020\u2014\u0020hex\u0020encoding\u0020for\u0020binary\u0020data\u0020\u0028ISO\u002032000\u002D2\u0020\u00A77.4.2\u0029.",
            "url": "classes/Phpdftk-Filters-AsciiHexFilter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\AsciiHexFilter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-AsciiHexFilter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\AsciiHexFilter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-AsciiHexFilter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\CCITTFaxFilter",
            "name": "CCITTFaxFilter",
            "summary": "CCITTFaxDecode\u0020filter\u0020\u2014\u0020ITU\u002DT\u0020T.4\u0020\u0028Group\u00203\u0029\u0020and\u0020T.6\u0020\u0028Group\u00204\u0029\u0020fax\u0020codec.",
            "url": "classes/Phpdftk-Filters-CCITTFaxFilter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\CCITTFaxFilter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Filters-CCITTFaxFilter.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\CCITTFaxFilter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-CCITTFaxFilter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\CCITTFaxFilter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-CCITTFaxFilter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FilterInterface",
            "name": "FilterInterface",
            "summary": "Symmetric\u0020encode\/decode\u0020contract\u0020for\u0020PDF\u0020stream\u0020filters\u0020\u0028ISO\u002032000\u002D2\u0020\u00A77.4\u0029.",
            "url": "classes/Phpdftk-Filters-FilterInterface.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FilterInterface\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-FilterInterface.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FilterInterface\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-FilterInterface.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FlateFilter",
            "name": "FlateFilter",
            "summary": "FlateDecode\u0020\u2014\u0020zlib\/deflate\u0020compression\u0020\u0028ISO\u002032000\u002D2\u0020\u00A77.4.4\u0029.",
            "url": "classes/Phpdftk-Filters-FlateFilter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FlateFilter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Filters-FlateFilter.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FlateFilter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-FlateFilter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\FlateFilter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-FlateFilter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\Jbig2Filter",
            "name": "Jbig2Filter",
            "summary": "JBIG2Decode\u0020filter\u0020\u2014\u0020ISO\u002014492\u0020\/\u0020ITU\u002DT\u0020T.88\u0020codec.",
            "url": "classes/Phpdftk-Filters-Jbig2Filter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\Jbig2Filter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Filters-Jbig2Filter.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\Jbig2Filter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-Jbig2Filter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\Jbig2Filter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-Jbig2Filter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\LzwFilter",
            "name": "LzwFilter",
            "summary": "LZW\u0020filter\u0020\u2014\u0020decode\/encode\u0020per\u0020ISO\u002032000\u002D2\u0020\u00A77.4.4.2.",
            "url": "classes/Phpdftk-Filters-LzwFilter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\LzwFilter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Filters-LzwFilter.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\LzwFilter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-LzwFilter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\LzwFilter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-LzwFilter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\PredictorFilter",
            "name": "PredictorFilter",
            "summary": "PDF\u0020predictor\u0020filter\u0020\u2014\u0020applies\/removes\u0020PNG\u0020and\u0020TIFF\u0020prediction\nas\u0020specified\u0020in\u0020ISO\u002032000\u002D2\u0020\u00A77.4.4.4.",
            "url": "classes/Phpdftk-Filters-PredictorFilter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\PredictorFilter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Filters-PredictorFilter.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\PredictorFilter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-PredictorFilter.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\PredictorFilter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-PredictorFilter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\RunLengthFilter",
            "name": "RunLengthFilter",
            "summary": "RunLengthDecode\u0020\u2014\u0020basic\u0020run\u002Dlength\u0020encoding\u0020\u0028ISO\u002032000\u002D2\u0020\u00A77.4.5\u0029.",
            "url": "classes/Phpdftk-Filters-RunLengthFilter.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\RunLengthFilter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-RunLengthFilter.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Filters\\RunLengthFilter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Phpdftk-Filters-RunLengthFilter.html#method_decode"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Filters",
            "name": "Filters",
            "summary": "",
            "url": "namespaces/phpdftk-filters.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
