Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener",
            "name": "AnnotationFlattener",
            "summary": "Flatten\u0020annotations\u0020into\u0020page\u0020content,\u0020making\u0020them\u0020non\u002Dinteractive.",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AflattenAll\u0028\u0029",
            "name": "flattenAll",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_flattenAll"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AflattenType\u0028\u0029",
            "name": "flattenType",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_flattenType"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AflattenForms\u0028\u0029",
            "name": "flattenForms",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_flattenForms"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\AnnotationFlattener\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-AnnotationFlattener.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Bookmark\\BookmarkEntry",
            "name": "BookmarkEntry",
            "summary": "A\u0020bookmark\u0020\u0028outline\u0020item\u0029\u0020for\u0020the\u0020toolkit\u0020API.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Bookmark-BookmarkEntry.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Bookmark\\BookmarkEntry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Bookmark-BookmarkEntry.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Bookmark\\BookmarkEntry\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Bookmark-BookmarkEntry.html#property_title"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Bookmark\\BookmarkEntry\u003A\u003A\u0024pageNumber",
            "name": "pageNumber",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Bookmark-BookmarkEntry.html#property_pageNumber"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Bookmark\\BookmarkEntry\u003A\u003A\u0024children",
            "name": "children",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Bookmark-BookmarkEntry.html#property_children"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor",
            "name": "BookmarkEditor",
            "summary": "Add,\u0020replace,\u0020read,\u0020or\u0020remove\u0020PDF\u0020bookmarks\u0020\u0028outlines\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AgetBookmarks\u0028\u0029",
            "name": "getBookmarks",
            "summary": "Read\u0020existing\u0020bookmarks\u0020from\u0020the\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_getBookmarks"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AhasBookmarks\u0028\u0029",
            "name": "hasBookmarks",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_hasBookmarks"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AsetBookmarks\u0028\u0029",
            "name": "setBookmarks",
            "summary": "Replace\u0020all\u0020bookmarks\u0020with\u0020the\u0020given\u0020entries.",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_setBookmarks"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AaddBookmark\u0028\u0029",
            "name": "addBookmark",
            "summary": "Add\u0020a\u0020single\u0020bookmark\u0020\u0028appended\u0020to\u0020existing\u0020bookmarks\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_addBookmark"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AremoveBookmarks\u0028\u0029",
            "name": "removeBookmarks",
            "summary": "Remove\u0020all\u0020bookmarks\u0020from\u0020the\u0020document.",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_removeBookmarks"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\BookmarkEditor\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-BookmarkEditor.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod",
            "name": "EncryptionMethod",
            "summary": "PDF\u0020encryption\u0020algorithms\u0020mapped\u0020to\u0020their\u0020encryption\u0020dictionary\u0020revisions.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod\u003A\u003ARc440",
            "name": "Rc440",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html#enumcase_Rc440"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod\u003A\u003ARc4128",
            "name": "Rc4128",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html#enumcase_Rc4128"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod\u003A\u003AAes128",
            "name": "Aes128",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html#enumcase_Aes128"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod\u003A\u003AAes256",
            "name": "Aes256",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html#enumcase_Aes256"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod\u003A\u003APublicKeyAes128",
            "name": "PublicKeyAes128",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html#enumcase_PublicKeyAes128"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\EncryptionMethod\u003A\u003APublicKeyAes256",
            "name": "PublicKeyAes256",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-EncryptionMethod.html#enumcase_PublicKeyAes256"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission",
            "name": "Permission",
            "summary": "PDF\u0020permission\u0020flags\u0020\u2014\u0020mirrors\u0020PdfEncryptor\u0020constants\u0020for\u0020convenience.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003APRINT",
            "name": "PRINT",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_PRINT"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003AMODIFY",
            "name": "MODIFY",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_MODIFY"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003ACOPY",
            "name": "COPY",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_COPY"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003AANNOTATE",
            "name": "ANNOTATE",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_ANNOTATE"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003AFILL_FORMS",
            "name": "FILL_FORMS",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_FILL_FORMS"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003AACCESSIBILITY",
            "name": "ACCESSIBILITY",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_ACCESSIBILITY"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003AASSEMBLE",
            "name": "ASSEMBLE",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_ASSEMBLE"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003APRINT_HIGH",
            "name": "PRINT_HIGH",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_PRINT_HIGH"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption\\Permission\u003A\u003AALL",
            "name": "ALL",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Encryption-Permission.html#constant_ALL"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo",
            "name": "FieldInfo",
            "summary": "Read\u002Donly\u0020snapshot\u0020of\u0020a\u0020form\u0020field\u0027s\u0020properties.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_name"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_type"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_value"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_flags"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024rect",
            "name": "rect",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_rect"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024maxLen",
            "name": "maxLen",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_maxLen"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldInfo\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldInfo.html#property_options"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldType",
            "name": "FieldType",
            "summary": "PDF\u0020interactive\u0020form\u0020field\u0020types\u0020\u0028ISO\u002032000\u002D2\u0020Table\u0020226\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldType.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldType\u003A\u003AText",
            "name": "Text",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldType.html#enumcase_Text"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldType\u003A\u003AButton",
            "name": "Button",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldType.html#enumcase_Button"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldType\u003A\u003AChoice",
            "name": "Choice",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldType.html#enumcase_Choice"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form\\FieldType\u003A\u003ASignature",
            "name": "Signature",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Form-FieldType.html#enumcase_Signature"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller",
            "name": "FormFiller",
            "summary": "Fill\u0020interactive\u0020PDF\u0020form\u0020fields\u0020\u0028AcroForm\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AgetFieldNames\u0028\u0029",
            "name": "getFieldNames",
            "summary": "Get\u0020all\u0020field\u0020names\u0020in\u0020the\u0020form.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_getFieldNames"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AgetFieldInfo\u0028\u0029",
            "name": "getFieldInfo",
            "summary": "Get\u0020detailed\u0020information\u0020about\u0020a\u0020specific\u0020field.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_getFieldInfo"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AgetFieldValues\u0028\u0029",
            "name": "getFieldValues",
            "summary": "Get\u0020all\u0020field\u0020values\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_getFieldValues"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AhasField\u0028\u0029",
            "name": "hasField",
            "summary": "Check\u0020whether\u0020a\u0020field\u0020exists\u0020in\u0020the\u0020form.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_hasField"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003Afill\u0028\u0029",
            "name": "fill",
            "summary": "Set\u0020the\u0020value\u0020of\u0020a\u0020text\u0020or\u0020choice\u0020field.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_fill"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AfillMany\u0028\u0029",
            "name": "fillMany",
            "summary": "Fill\u0020multiple\u0020fields\u0020at\u0020once.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_fillMany"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020or\u0020uncheck\u0020a\u0020checkbox\u0020field.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003Aselect\u0028\u0029",
            "name": "select",
            "summary": "Select\u0020an\u0020option\u0020in\u0020a\u0020choice\u0020field.",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_select"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\FormFiller\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-FormFiller.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label\\LabelStyle",
            "name": "LabelStyle",
            "summary": "Page\u0020label\u0020numbering\u0020styles\u0020\u0028ISO\u002032000\u002D2\u0020Table\u0020163\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Label-LabelStyle.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label\\LabelStyle\u003A\u003AArabic",
            "name": "Arabic",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Label-LabelStyle.html#enumcase_Arabic"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label\\LabelStyle\u003A\u003ARomanLower",
            "name": "RomanLower",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Label-LabelStyle.html#enumcase_RomanLower"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label\\LabelStyle\u003A\u003ARomanUpper",
            "name": "RomanUpper",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Label-LabelStyle.html#enumcase_RomanUpper"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label\\LabelStyle\u003A\u003AAlphaLower",
            "name": "AlphaLower",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Label-LabelStyle.html#enumcase_AlphaLower"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label\\LabelStyle\u003A\u003AAlphaUpper",
            "name": "AlphaUpper",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Label-LabelStyle.html#enumcase_AlphaUpper"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner",
            "name": "LtvSigner",
            "summary": "Add\u0020LTV\u0020\u0028Long\u002DTerm\u0020Validation\u0029\u0020data\u0020to\u0020signed\u0020PDFs\u0020\u2014\u0020PAdES\u0020B\u002DLT\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AsetOcspClient\u0028\u0029",
            "name": "setOcspClient",
            "summary": "Set\u0020the\u0020OCSP\u0020client\u0020for\u0020online\u0020revocation\u0020checking.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_setOcspClient"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AsetCrlClient\u0028\u0029",
            "name": "setCrlClient",
            "summary": "Set\u0020the\u0020CRL\u0020client\u0020for\u0020online\u0020revocation\u0020checking.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_setCrlClient"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AaddOcspResponse\u0028\u0029",
            "name": "addOcspResponse",
            "summary": "Pre\u002Dload\u0020a\u0020DER\u002Dencoded\u0020OCSP\u0020response\u0020\u0028for\u0020offline\/testing\u0020use\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_addOcspResponse"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AaddCrl\u0028\u0029",
            "name": "addCrl",
            "summary": "Pre\u002Dload\u0020a\u0020DER\u002Dencoded\u0020CRL\u0020\u0028for\u0020offline\/testing\u0020use\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_addCrl"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AaddCertificate\u0028\u0029",
            "name": "addCertificate",
            "summary": "Add\u0020an\u0020extra\u0020DER\u002Dencoded\u0020certificate\u0020to\u0020include\u0020in\u0020the\u0020DSS.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_addCertificate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AforSignature\u0028\u0029",
            "name": "forSignature",
            "summary": "Target\u0020a\u0020specific\u0020signature\u0020field\u0020by\u0020name.\u0020Can\u0020be\u0020called\u0020multiple\u0020times.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_forSignature"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AgetWarnings\u0028\u0029",
            "name": "getWarnings",
            "summary": "Get\u0020non\u002Dfatal\u0020warnings\u0020from\u0020OCSP\/CRL\u0020fetching.",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_getWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\LtvSigner\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-LtvSigner.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor",
            "name": "MetadataEditor",
            "summary": "Read\u0020and\u0020modify\u0020PDF\u0020document\u0020metadata\u0020\u0028Info\u0020dictionary\u0029.",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getTitle"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetAuthor\u0028\u0029",
            "name": "getAuthor",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getAuthor"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getSubject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetKeywords\u0028\u0029",
            "name": "getKeywords",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getKeywords"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetCreator\u0028\u0029",
            "name": "getCreator",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getCreator"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetProducer\u0028\u0029",
            "name": "getProducer",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getProducer"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetCreationDate\u0028\u0029",
            "name": "getCreationDate",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getCreationDate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetModDate\u0028\u0029",
            "name": "getModDate",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getModDate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetTrapped\u0028\u0029",
            "name": "getTrapped",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getTrapped"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getAll"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setTitle"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetAuthor\u0028\u0029",
            "name": "setAuthor",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setAuthor"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetSubject\u0028\u0029",
            "name": "setSubject",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setSubject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetKeywords\u0028\u0029",
            "name": "setKeywords",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setKeywords"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetCreator\u0028\u0029",
            "name": "setCreator",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setCreator"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetProducer\u0028\u0029",
            "name": "setProducer",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setProducer"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetCreationDate\u0028\u0029",
            "name": "setCreationDate",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setCreationDate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetModDate\u0028\u0029",
            "name": "setModDate",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setModDate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetTrapped\u0028\u0029",
            "name": "setTrapped",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setTrapped"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AsetCustom\u0028\u0029",
            "name": "setCustom",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_setCustom"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataEditor\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataEditor.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo",
            "name": "MetadataInfo",
            "summary": "Read\u002Donly\u0020snapshot\u0020of\u0020a\u0020PDF\u0027s\u0020Info\u0020dictionary\u0020fields.",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_title"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024author",
            "name": "author",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_author"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_subject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024keywords",
            "name": "keywords",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_keywords"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024creator",
            "name": "creator",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_creator"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024producer",
            "name": "producer",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_producer"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024creationDate",
            "name": "creationDate",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_creationDate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024modDate",
            "name": "modDate",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_modDate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\MetadataInfo\u003A\u003A\u0024trapped",
            "name": "trapped",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-MetadataInfo.html#property_trapped"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler",
            "name": "PageLabeler",
            "summary": "Set\u0020page\u0020numbering\u0020labels\u0020on\u0020a\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AsetLabels\u0028\u0029",
            "name": "setLabels",
            "summary": "Set\u0020a\u0020label\u0020range\u0020starting\u0020at\u0020the\u0020given\u0020page.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_setLabels"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AsetRomanNumerals\u0028\u0029",
            "name": "setRomanNumerals",
            "summary": "Set\u0020roman\u0020numeral\u0020labels\u0020for\u0020a\u0020page\u0020range.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_setRomanNumerals"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AsetAlphabetic\u0028\u0029",
            "name": "setAlphabetic",
            "summary": "Set\u0020alphabetic\u0020labels\u0020for\u0020a\u0020page\u0020range.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_setAlphabetic"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AsetArabic\u0028\u0029",
            "name": "setArabic",
            "summary": "Set\u0020arabic\u0020numeral\u0020labels\u0020starting\u0020at\u0020a\u0020page.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_setArabic"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AremoveLabels\u0028\u0029",
            "name": "removeLabels",
            "summary": "Remove\u0020all\u0020page\u0020labels\u0020from\u0020the\u0020document.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_removeLabels"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageLabeler\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageLabeler.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector",
            "name": "PageSelector",
            "summary": "Selects\u0020which\u0020pages\u0020an\u0020operation\u0020applies\u0020to.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_all"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Apages\u0028\u0029",
            "name": "pages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_pages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Arange\u0028\u0029",
            "name": "range",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_range"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Aeven\u0028\u0029",
            "name": "even",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_even"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Aodd\u0028\u0029",
            "name": "odd",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_odd"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Check\u0020if\u0020a\u0020page\u0020number\u0020matches\u0020this\u0020selector.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_matches"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSelector\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "Resolve\u0020matching\u0020page\u0020indices\u0020\u00280\u002Dbased\u0029\u0020for\u0020a\u0020document.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSelector.html#method_resolve"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer",
            "name": "PageSlicer",
            "summary": "Extract,\u0020reorder,\u0020remove,\u0020and\u0020split\u0020pages\u0020from\u0020a\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Akeep\u0028\u0029",
            "name": "keep",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_keep"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AkeepPages\u0028\u0029",
            "name": "keepPages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_keepPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AkeepRange\u0028\u0029",
            "name": "keepRange",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_keepRange"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_remove"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AremovePages\u0028\u0029",
            "name": "removePages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_removePages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Areorder\u0028\u0029",
            "name": "reorder",
            "summary": "Reorder\u0020pages.\u0020Arguments\u0020are\u00201\u002Dbased\u0020page\u0020numbers\u0020in\u0020desired\u0020order.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_reorder"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_reverse"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Asplit\u0028\u0029",
            "name": "split",
            "summary": "Split\u0020the\u0020PDF\u0020at\u0020a\u0020given\u0020page\u0020number.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_split"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageSlicer\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageSlicer.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer",
            "name": "PageTransformer",
            "summary": "Transform\u0020page\u0020geometry\u0020\u2014\u0020rotate,\u0020scale,\u0020and\u0020set\u0020page\u0020boxes.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003Arotate\u0028\u0029",
            "name": "rotate",
            "summary": "Rotate\u0020pages\u0020by\u0020the\u0020given\u0020angle.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_rotate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003Ascale\u0028\u0029",
            "name": "scale",
            "summary": "Scale\u0020pages\u0020by\u0020a\u0020uniform\u0020factor.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_scale"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AscaleTo\u0028\u0029",
            "name": "scaleTo",
            "summary": "Scale\u0020pages\u0020to\u0020fit\u0020the\u0020given\u0020dimensions.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_scaleTo"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AsetCropBox\u0028\u0029",
            "name": "setCropBox",
            "summary": "Set\u0020the\u0020CropBox\u0020on\u0020selected\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_setCropBox"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AsetMediaBox\u0028\u0029",
            "name": "setMediaBox",
            "summary": "Set\u0020the\u0020MediaBox\u0020on\u0020selected\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_setMediaBox"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AsetTrimBox\u0028\u0029",
            "name": "setTrimBox",
            "summary": "Set\u0020the\u0020TrimBox\u0020on\u0020selected\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_setTrimBox"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AsetBleedBox\u0028\u0029",
            "name": "setBleedBox",
            "summary": "Set\u0020the\u0020BleedBox\u0020on\u0020selected\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_setBleedBox"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PageTransformer\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PageTransformer.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt",
            "name": "PdfEncrypt",
            "summary": "Apply,\u0020change,\u0020or\u0020remove\u0020encryption\u0020on\u0020existing\u0020PDFs.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003Aencrypt\u0028\u0029",
            "name": "encrypt",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_encrypt"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003Adecrypt\u0028\u0029",
            "name": "decrypt",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_decrypt"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AchangePasswords\u0028\u0029",
            "name": "changePasswords",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_changePasswords"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AsetPermissions\u0028\u0029",
            "name": "setPermissions",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_setPermissions"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AisEncrypted\u0028\u0029",
            "name": "isEncrypted",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_isEncrypted"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfEncrypt\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfEncrypt.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger",
            "name": "PdfMerger",
            "summary": "Combine\u0020multiple\u0020PDFs\u0020into\u0020one\u0020document.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_create"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AaddFile\u0028\u0029",
            "name": "addFile",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_addFile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AaddString\u0028\u0029",
            "name": "addString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_addString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AaddPages\u0028\u0029",
            "name": "addPages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_addPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AgetSourceCount\u0028\u0029",
            "name": "getSourceCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_getSourceCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AgetTotalPageCount\u0028\u0029",
            "name": "getTotalPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_getTotalPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "Build\u0020the\u0020merged\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfMerger\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfMerger.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper",
            "name": "PdfStamper",
            "summary": "Add\u0020text\u0020overlays,\u0020watermarks,\u0020page\u0020numbers,\u0020headers\u0020and\u0020footers\u0020to\u0020PDFs.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AstampText\u0028\u0029",
            "name": "stampText",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_stampText"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003Awatermark\u0028\u0029",
            "name": "watermark",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_watermark"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AaddPageNumbers\u0028\u0029",
            "name": "addPageNumbers",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_addPageNumbers"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_header"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003Afooter\u0028\u0029",
            "name": "footer",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_footer"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AstampImage\u0028\u0029",
            "name": "stampImage",
            "summary": "Overlay\u0020a\u0020JPEG\u0020or\u0020PNG\u0020image\u0020at\u0020a\u0020given\u0020position\u0020on\u0020selected\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_stampImage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AstampPdf\u0028\u0029",
            "name": "stampPdf",
            "summary": "Overlay\u0020a\u0020page\u0020from\u0020another\u0020PDF\u0020at\u0020a\u0020given\u0020position\u0020on\u0020selected\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_stampPdf"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\PdfStamper\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-PdfStamper.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea",
            "name": "RedactionArea",
            "summary": "Defines\u0020an\u0020area\u0020on\u0020a\u0020page\u0020to\u0020redact.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea\u003A\u003A\u0024pageIndex",
            "name": "pageIndex",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html#property_pageIndex"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea\u003A\u003A\u0024x",
            "name": "x",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html#property_x"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html#property_y"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html#property_width"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction\\RedactionArea\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Redaction-RedactionArea.html#property_height"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\ImageStampStyle",
            "name": "ImageStampStyle",
            "summary": "Style\u0020configuration\u0020for\u0020image\u0020and\u0020PDF\u0020stamps.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-ImageStampStyle.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\ImageStampStyle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-ImageStampStyle.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\ImageStampStyle\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-ImageStampStyle.html#property_width"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\ImageStampStyle\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-ImageStampStyle.html#property_height"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\ImageStampStyle\u003A\u003A\u0024opacity",
            "name": "opacity",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-ImageStampStyle.html#property_opacity"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition",
            "name": "StampPosition",
            "summary": "Predefined\u0020stamp\u0020positions\u0020on\u0020a\u0020page.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003AcomputeCoordinates\u0028\u0029",
            "name": "computeCoordinates",
            "summary": "Compute\u0020X\/Y\u0020coordinates\u0020for\u0020text\u0020placement\u0020given\u0020page\u0020dimensions\u0020and\u0020margins.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#method_computeCoordinates"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ATopLeft",
            "name": "TopLeft",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_TopLeft"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ATopCenter",
            "name": "TopCenter",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_TopCenter"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ATopRight",
            "name": "TopRight",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_TopRight"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ACenter",
            "name": "Center",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_Center"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ABottomLeft",
            "name": "BottomLeft",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_BottomLeft"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ABottomCenter",
            "name": "BottomCenter",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_BottomCenter"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampPosition\u003A\u003ABottomRight",
            "name": "BottomRight",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampPosition.html#enumcase_BottomRight"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle",
            "name": "StampStyle",
            "summary": "Style\u0020configuration\u0020for\u0020text\u0020stamps.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024fontSize",
            "name": "fontSize",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_fontSize"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024fontName",
            "name": "fontName",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_fontName"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024r",
            "name": "r",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_r"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024g",
            "name": "g",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_g"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024b",
            "name": "b",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_b"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024opacity",
            "name": "opacity",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_opacity"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\StampStyle\u003A\u003A\u0024rotation",
            "name": "rotation",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-StampStyle.html#property_rotation"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle",
            "name": "WatermarkStyle",
            "summary": "Style\u0020configuration\u0020for\u0020watermark\u0020text.",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A\u0024fontSize",
            "name": "fontSize",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#property_fontSize"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A\u0024r",
            "name": "r",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#property_r"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A\u0024g",
            "name": "g",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#property_g"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A\u0024b",
            "name": "b",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#property_b"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A\u0024opacity",
            "name": "opacity",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#property_opacity"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper\\WatermarkStyle\u003A\u003A\u0024rotation",
            "name": "rotation",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-Stamper-WatermarkStyle.html#property_rotation"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextBlock",
            "name": "TextBlock",
            "summary": "A\u0020block\u0020of\u0020text\u0020extracted\u0020from\u0020a\u0020PDF\u0020page,\u0020grouped\u0020by\u0020font\/size.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextBlock.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextBlock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextBlock.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextBlock\u003A\u003A\u0024text",
            "name": "text",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextBlock.html#property_text"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextBlock\u003A\u003A\u0024fontName",
            "name": "fontName",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextBlock.html#property_fontName"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextBlock\u003A\u003A\u0024fontSize",
            "name": "fontSize",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextBlock.html#property_fontSize"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor",
            "name": "TextExtractor",
            "summary": "Extract\u0020text\u0020from\u0020PDFs\u0020\u2014\u0020per\u0020page,\u0020full\u0020document,\u0020or\u0020with\u0020search.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003Apage\u0028\u0029",
            "name": "page",
            "summary": "Extract\u0020text\u0020from\u0020a\u0020single\u0020page.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_page"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AallPages\u0028\u0029",
            "name": "allPages",
            "summary": "Extract\u0020text\u0020from\u0020all\u0020pages,\u0020joined\u0020by\u0020a\u0020separator.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_allPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AperPage\u0028\u0029",
            "name": "perPage",
            "summary": "Extract\u0020text\u0020per\u0020page.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_perPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003ApageWithPositions\u0028\u0029",
            "name": "pageWithPositions",
            "summary": "Extract\u0020text\u0020with\u0020precise\u0020positioning\u0020from\u0020a\u0020single\u0020page.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_pageWithPositions"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AallPagesWithPositions\u0028\u0029",
            "name": "allPagesWithPositions",
            "summary": "Extract\u0020text\u0020with\u0020precise\u0020positioning\u0020from\u0020all\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_allPagesWithPositions"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003Acontains\u0028\u0029",
            "name": "contains",
            "summary": "Check\u0020if\u0020a\u0020text\u0020string\u0020appears\u0020anywhere\u0020in\u0020the\u0020document.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_contains"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020a\u0020text\u0020string\u0020across\u0020all\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_search"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AsearchPattern\u0028\u0029",
            "name": "searchPattern",
            "summary": "Search\u0020for\u0020a\u0020regex\u0020pattern\u0020across\u0020all\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_searchPattern"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextExtractor\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextExtractor.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextMatch",
            "name": "TextMatch",
            "summary": "A\u0020single\u0020text\u0020search\u0020match\u0020within\u0020a\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextMatch.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextMatch\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextMatch.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextMatch\u003A\u003A\u0024pageNumber",
            "name": "pageNumber",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextMatch.html#property_pageNumber"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextMatch\u003A\u003A\u0024text",
            "name": "text",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextMatch.html#property_text"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextMatch\u003A\u003A\u0024offset",
            "name": "offset",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextMatch.html#property_offset"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor",
            "name": "TextRedactor",
            "summary": "Redact\u0020text\u0020or\u0020areas\u0020from\u0020PDF\u0020pages\u0020by\u0020drawing\u0020filled\u0020rectangles.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AredactText\u0028\u0029",
            "name": "redactText",
            "summary": "Mark\u0020a\u0020text\u0020string\u0020for\u0020redaction\u0020across\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_redactText"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AredactPattern\u0028\u0029",
            "name": "redactPattern",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_redactPattern"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AredactArea\u0028\u0029",
            "name": "redactArea",
            "summary": "Mark\u0020a\u0020specific\u0020area\u0020for\u0020redaction.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_redactArea"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AsetRedactionColor\u0028\u0029",
            "name": "setRedactionColor",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_setRedactionColor"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003Aapply\u0028\u0029",
            "name": "apply",
            "summary": "Apply\u0020all\u0020marked\u0020redactions.\u0020Must\u0020be\u0020called\u0020before\u0020save\/toBytes.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_apply"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AgetRedactionCount\u0028\u0029",
            "name": "getRedactionCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_getRedactionCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_save"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AtoBytes\u0028\u0029",
            "name": "toBytes",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_toBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AgetVersionWarnings\u0028\u0029",
            "name": "getVersionWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_getVersionWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextRedactor\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextRedactor.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextSearchResults",
            "name": "TextSearchResults",
            "summary": "Collection\u0020of\u0020text\u0020search\u0020matches\u0020across\u0020a\u0020PDF\u0020document.",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextSearchResults.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextSearchResults\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextSearchResults.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextSearchResults\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextSearchResults.html#method_count"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextSearchResults\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextSearchResults.html#method_all"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextSearchResults\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextSearchResults.html#method_first"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\TextSearchResults\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Toolkit-TextSearchResults.html#method_getIterator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit",
            "name": "Toolkit",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf",
            "name": "Pdf",
            "summary": "",
            "url": "namespaces/phpdftk-pdf.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Bookmark",
            "name": "Bookmark",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit-bookmark.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Encryption",
            "name": "Encryption",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit-encryption.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit-form.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Label",
            "name": "Label",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit-label.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Redaction",
            "name": "Redaction",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit-redaction.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Toolkit\\Stamper",
            "name": "Stamper",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-toolkit-stamper.html"
        }            ]
);
