Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData",
            "name": "CffData",
            "summary": "Parsed\u0020CFF\u0020\u0028Compact\u0020Font\u0020Format\u0029\u0020table\u0020structure.",
            "url": "classes/Phpdftk-FontParser-CffData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024major",
            "name": "major",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_major"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024minor",
            "name": "minor",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_minor"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024hdrSize",
            "name": "hdrSize",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_hdrSize"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024nameIndexData",
            "name": "nameIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_nameIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024topDictOperators",
            "name": "topDictOperators",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_topDictOperators"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024stringIndexData",
            "name": "stringIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_stringIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024globalSubrIndexData",
            "name": "globalSubrIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_globalSubrIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024charStrings",
            "name": "charStrings",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_charStrings"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024privateDictData",
            "name": "privateDictData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_privateDictData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024localSubrIndexData",
            "name": "localSubrIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_localSubrIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024charset",
            "name": "charset",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_charset"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024fdArrayData",
            "name": "fdArrayData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_fdArrayData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024fdSelectData",
            "name": "fdSelectData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_fdSelectData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffParser",
            "name": "CffParser",
            "summary": "Parses\u0020a\u0020CFF\u0020\u0028Compact\u0020Font\u0020Format\u0029\u0020binary\u0020table\u0020into\u0020a\u0020CffData\u0020structure.",
            "url": "classes/Phpdftk-FontParser-CffParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffSubsetter",
            "name": "CffSubsetter",
            "summary": "Produces\u0020a\u0020minimal\u0020CFF\u0020table\u0020containing\u0020only\u0020requested\u0020glyphs.",
            "url": "classes/Phpdftk-FontParser-CffSubsetter.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffSubsetter\u003A\u003Asubset\u0028\u0029",
            "name": "subset",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffSubsetter.html#method_subset"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffSubsetter\u003A\u003AgetGidMap\u0028\u0029",
            "name": "getGidMap",
            "summary": "The\u0020old\u0020\u2192\u0020new\u0020GID\u0020map\u0020from\u0020the\u0020most\u0020recent\u0020\u0060subset\u0028\u0029\u0060\u0020call.\u0020Returns\nan\u0020empty\u0020array\u0020if\u0020\u0060subset\u0028\u0029\u0060\u0020has\u0020not\u0020been\u0020called\u0020yet.",
            "url": "classes/Phpdftk-FontParser-CffSubsetter.html#method_getGidMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\GsubParser",
            "name": "GsubParser",
            "summary": "Parses\u0020GSUB\u0020\u0028Glyph\u0020Substitution\u0029\u0020table\u0020for\u0020ligature\u0020features.",
            "url": "classes/Phpdftk-FontParser-GsubParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\GsubParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-GsubParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\KerningParser",
            "name": "KerningParser",
            "summary": "Parses\u0020kerning\u0020data\u0020from\u0020GPOS\u0020table\u0020\u0028or\u0020legacy\u0020kern\u0020table\u0029.",
            "url": "classes/Phpdftk-FontParser-KerningParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\KerningParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-KerningParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData",
            "name": "MathTableData",
            "summary": "Parsed\u0020\u0060MATH\u0060\u0020table\u0020from\u0020an\u0020OpenType\u0020math\u0020font\u0020\u0028Latin\u0020Modern\u0020Math,\nSTIX\u0020Two\u0020Math,\u0020Cambria\u0020Math,\u0020...\u0029.\u0020Defined\u0020in\u0020the\u0020OpenType\u0020spec\nhttps\u003A\/\/learn.microsoft.com\/en\u002Dus\/typography\/opentype\/spec\/math.",
            "url": "classes/Phpdftk-FontParser-MathTableData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003AhasMathConstants\u0028\u0029",
            "name": "hasMathConstants",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method_hasMathConstants"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003AhasMathGlyphInfo\u0028\u0029",
            "name": "hasMathGlyphInfo",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method_hasMathGlyphInfo"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003AhasMathVariants\u0028\u0029",
            "name": "hasMathVariants",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method_hasMathVariants"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024majorVersion",
            "name": "majorVersion",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_majorVersion"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024minorVersion",
            "name": "minorVersion",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_minorVersion"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024mathConstantsBytes",
            "name": "mathConstantsBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_mathConstantsBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024mathGlyphInfoBytes",
            "name": "mathGlyphInfoBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_mathGlyphInfoBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024mathVariantsBytes",
            "name": "mathVariantsBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_mathVariantsBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData",
            "name": "OpenTypeData",
            "summary": "Parsed\u0020OpenType\u0020CFF\u0020font\u0020data\u0020\u2014\u0020metrics,\u0020glyph\u0020widths,\u0020and\u0020raw\u0020CFF\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_postScriptName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024familyName",
            "name": "familyName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_familyName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024ascent",
            "name": "ascent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_ascent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024descent",
            "name": "descent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_descent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_capHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024xHeight",
            "name": "xHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_xHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_italicAngle"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024stemV",
            "name": "stemV",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_stemV"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_flags"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024fontBBox",
            "name": "fontBBox",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_fontBBox"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024charWidths",
            "name": "charWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_charWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024unicodeMap",
            "name": "unicodeMap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_unicodeMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024cffBytes",
            "name": "cffBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_cffBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024fontBytes",
            "name": "fontBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_fontBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024embeddingAllowed",
            "name": "embeddingAllowed",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_embeddingAllowed"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024unitsPerEm",
            "name": "unitsPerEm",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_unitsPerEm"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024fullUnicodeToGid",
            "name": "fullUnicodeToGid",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_fullUnicodeToGid"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024glyphWidths",
            "name": "glyphWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_glyphWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024kernPairs",
            "name": "kernPairs",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_kernPairs"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024ligatures",
            "name": "ligatures",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_ligatures"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024verticalWidths",
            "name": "verticalWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_verticalWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024underlinePosition",
            "name": "underlinePosition",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_underlinePosition"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024underlineThickness",
            "name": "underlineThickness",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_underlineThickness"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024mathTable",
            "name": "mathTable",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_mathTable"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser",
            "name": "OpenTypeParser",
            "summary": "Parser\u0020for\u0020OpenType\u0020fonts\u0020with\u0020CFF\u0020outlines\u0020\u0028sfVersion\u0020\u0022OTTO\u0022\u0029.",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Create\u0020a\u0020parser\u0020from\u0020raw\u0020font\u0020bytes\u0020instead\u0020of\u0020a\u0020file\u0020path.",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html#method_fromBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TextShaper",
            "name": "TextShaper",
            "summary": "Simple\u0020text\u0020shaper\u0020for\u0020Latin\u0020ligature\u0020substitution.",
            "url": "classes/Phpdftk-FontParser-TextShaper.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TextShaper\u003A\u003AapplyLigatures\u0028\u0029",
            "name": "applyLigatures",
            "summary": "Apply\u0020ligature\u0020substitutions\u0020to\u0020a\u0020GID\u0020sequence.",
            "url": "classes/Phpdftk-FontParser-TextShaper.html#method_applyLigatures"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData",
            "name": "TrueTypeData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_postScriptName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024familyName",
            "name": "familyName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_familyName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024ascent",
            "name": "ascent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_ascent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024descent",
            "name": "descent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_descent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_capHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024xHeight",
            "name": "xHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_xHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_italicAngle"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024stemV",
            "name": "stemV",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_stemV"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_flags"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024fontBBox",
            "name": "fontBBox",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_fontBBox"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024charWidths",
            "name": "charWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_charWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024unicodeMap",
            "name": "unicodeMap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_unicodeMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024fontBytes",
            "name": "fontBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_fontBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024embeddingAllowed",
            "name": "embeddingAllowed",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_embeddingAllowed"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024unitsPerEm",
            "name": "unitsPerEm",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_unitsPerEm"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024fullUnicodeToGid",
            "name": "fullUnicodeToGid",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_fullUnicodeToGid"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024glyphWidths",
            "name": "glyphWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_glyphWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024kernPairs",
            "name": "kernPairs",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_kernPairs"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024ligatures",
            "name": "ligatures",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_ligatures"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024isVariableFont",
            "name": "isVariableFont",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_isVariableFont"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024variationAxes",
            "name": "variationAxes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_variationAxes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024namedInstances",
            "name": "namedInstances",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_namedInstances"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser",
            "name": "TrueTypeParser",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Create\u0020a\u0020parser\u0020from\u0020raw\u0020font\u0020bytes\u0020instead\u0020of\u0020a\u0020file\u0020path.",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html#method_fromBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeSubsetter",
            "name": "TrueTypeSubsetter",
            "summary": "Produces\u0020a\u0020minimal\u0020valid\u0020TrueType\u0020font\u0020containing\u0020only\u0020requested\u0020glyphs.",
            "url": "classes/Phpdftk-FontParser-TrueTypeSubsetter.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeSubsetter\u003A\u003Asubset\u0028\u0029",
            "name": "subset",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeSubsetter.html#method_subset"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeSubsetter\u003A\u003AgetGidMap\u0028\u0029",
            "name": "getGidMap",
            "summary": "The\u0020old\u0020\u2192\u0020new\u0020GID\u0020map\u0020from\u0020the\u0020most\u0020recent\u0020\u0060subset\u0028\u0029\u0060\u0020call.\u0020Returns\nan\u0020empty\u0020array\u0020if\u0020\u0060subset\u0028\u0029\u0060\u0020has\u0020not\u0020been\u0020called\u0020yet.\u0020Callers\u0020use\u0020this\nto\u0020translate\u0020any\u0020pre\u002Dsubset\u0020GIDs\u0020they\u0020hold\u0020into\u0020the\u0020renumbered\u0020GIDs\nthat\u0020live\u0020in\u0020the\u0020emitted\u0020subset\u0020font.",
            "url": "classes/Phpdftk-FontParser-TrueTypeSubsetter.html#method_getGidMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data",
            "name": "Type1Data",
            "summary": "Parsed\u0020data\u0020from\u0020a\u0020Type\u00201\u0020font\u0020\u0028PFB\/PFA\u0029.",
            "url": "classes/Phpdftk-FontParser-Type1Data.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_postScriptName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024familyName",
            "name": "familyName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_familyName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024ascent",
            "name": "ascent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_ascent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024descent",
            "name": "descent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_descent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_capHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024xHeight",
            "name": "xHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_xHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_italicAngle"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024stemV",
            "name": "stemV",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_stemV"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_flags"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024fontBBox",
            "name": "fontBBox",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_fontBBox"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024charWidths",
            "name": "charWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_charWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024unicodeMap",
            "name": "unicodeMap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_unicodeMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024fontBytes",
            "name": "fontBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_fontBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024length1",
            "name": "length1",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_length1"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024length2",
            "name": "length2",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_length2"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024length3",
            "name": "length3",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_length3"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024glyphWidths",
            "name": "glyphWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_glyphWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024encoding",
            "name": "encoding",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_encoding"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser",
            "name": "Type1Parser",
            "summary": "Parses\u0020Type\u00201\u0020font\u0020files\u0020\u0028PFB\u0020binary\u0020and\u0020PFA\u0020ASCII\u0020formats\u0029.",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Create\u0020a\u0020parser\u0020from\u0020raw\u0020font\u0020bytes\u0020instead\u0020of\u0020a\u0020file\u0020path.",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html#method_fromBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser",
            "name": "Woff2Parser",
            "summary": "WOFF\u00202.0\u0020\u0028Web\u0020Open\u0020Font\u0020Format\u00202.0\u0029\u0020decompressor.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003Adecompress\u0028\u0029",
            "name": "decompress",
            "summary": "Decompress\u0020a\u0020WOFF2\u0020file\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_decompress"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003AdecompressBytes\u0028\u0029",
            "name": "decompressBytes",
            "summary": "Decompress\u0020WOFF2\u0020bytes\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_decompressBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003AisWoff2\u0028\u0029",
            "name": "isWoff2",
            "summary": "Detect\u0020whether\u0020bytes\u0020are\u0020a\u0020WOFF2\u0020file.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_isWoff2"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003AdetectFlavor\u0028\u0029",
            "name": "detectFlavor",
            "summary": "Detect\u0020the\u0020flavor\u0020\u0028TrueType\u0020or\u0020OpenType\u0020CFF\u0029\u0020of\u0020a\u0020WOFF2\u0020file.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_detectFlavor"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser",
            "name": "WoffParser",
            "summary": "WOFF\u0020\u0028Web\u0020Open\u0020Font\u0020Format\u00201.0\u0029\u0020decompressor.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003Adecompress\u0028\u0029",
            "name": "decompress",
            "summary": "Decompress\u0020a\u0020WOFF\u0020file\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_decompress"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003AdecompressBytes\u0028\u0029",
            "name": "decompressBytes",
            "summary": "Decompress\u0020WOFF\u0020bytes\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_decompressBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003AisWoff\u0028\u0029",
            "name": "isWoff",
            "summary": "Detect\u0020whether\u0020bytes\u0020are\u0020a\u0020WOFF\u0020file.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_isWoff"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003AdetectFlavor\u0028\u0029",
            "name": "detectFlavor",
            "summary": "Detect\u0020the\u0020flavor\u0020\u0028TrueType\u0020or\u0020OpenType\u0020CFF\u0029\u0020of\u0020a\u0020WOFF\u0020file.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_detectFlavor"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser",
            "name": "FontParser",
            "summary": "",
            "url": "namespaces/phpdftk-fontparser.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
