Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData",
            "name": "CffData",
            "summary": "Parsed\u0020CFF\u0020\u0028Compact\u0020Font\u0020Format\u0029\u0020table\u0020structure.",
            "url": "classes/Phpdftk-FontParser-CffData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024major",
            "name": "major",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_major"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024minor",
            "name": "minor",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_minor"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024hdrSize",
            "name": "hdrSize",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_hdrSize"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024nameIndexData",
            "name": "nameIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_nameIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024topDictOperators",
            "name": "topDictOperators",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_topDictOperators"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024stringIndexData",
            "name": "stringIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_stringIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024globalSubrIndexData",
            "name": "globalSubrIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_globalSubrIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024charStrings",
            "name": "charStrings",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_charStrings"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024privateDictData",
            "name": "privateDictData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_privateDictData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024localSubrIndexData",
            "name": "localSubrIndexData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_localSubrIndexData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024charset",
            "name": "charset",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_charset"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024fdArrayData",
            "name": "fdArrayData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_fdArrayData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffData\u003A\u003A\u0024fdSelectData",
            "name": "fdSelectData",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffData.html#property_fdSelectData"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffParser",
            "name": "CffParser",
            "summary": "Parses\u0020a\u0020CFF\u0020\u0028Compact\u0020Font\u0020Format\u0029\u0020binary\u0020table\u0020into\u0020a\u0020CffData\u0020structure.",
            "url": "classes/Phpdftk-FontParser-CffParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffSubsetter",
            "name": "CffSubsetter",
            "summary": "Produces\u0020a\u0020minimal\u0020CFF\u0020table\u0020containing\u0020only\u0020requested\u0020glyphs.",
            "url": "classes/Phpdftk-FontParser-CffSubsetter.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffSubsetter\u003A\u003Asubset\u0028\u0029",
            "name": "subset",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-CffSubsetter.html#method_subset"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\CffSubsetter\u003A\u003AgetGidMap\u0028\u0029",
            "name": "getGidMap",
            "summary": "The\u0020old\u0020\u2192\u0020new\u0020GID\u0020map\u0020from\u0020the\u0020most\u0020recent\u0020\u0060subset\u0028\u0029\u0060\u0020call.\u0020Returns\nan\u0020empty\u0020array\u0020if\u0020\u0060subset\u0028\u0029\u0060\u0020has\u0020not\u0020been\u0020called\u0020yet.",
            "url": "classes/Phpdftk-FontParser-CffSubsetter.html#method_getGidMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData",
            "name": "FontFaceData",
            "summary": "Common\u0020shape\u0020for\u0020a\u0020parsed\u0020font\u0020face\u0020\u2014\u0020the\u0020fields\u0020any\u0020downstream\nconsumer\u0020needs\u0020to\u0020lay\u0020out,\u0020shape,\u0020and\u0020embed\u0020text.",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_postScriptName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024familyName",
            "name": "familyName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_familyName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024ascent",
            "name": "ascent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_ascent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024descent",
            "name": "descent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_descent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_capHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024xHeight",
            "name": "xHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_xHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_italicAngle"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024stemV",
            "name": "stemV",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_stemV"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_flags"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024fontBBox",
            "name": "fontBBox",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_fontBBox"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024charWidths",
            "name": "charWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_charWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024unicodeMap",
            "name": "unicodeMap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_unicodeMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024fontBytes",
            "name": "fontBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_fontBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024embeddingAllowed",
            "name": "embeddingAllowed",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_embeddingAllowed"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024unitsPerEm",
            "name": "unitsPerEm",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_unitsPerEm"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024fullUnicodeToGid",
            "name": "fullUnicodeToGid",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_fullUnicodeToGid"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024glyphWidths",
            "name": "glyphWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_glyphWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024kernPairs",
            "name": "kernPairs",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_kernPairs"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024ligatures",
            "name": "ligatures",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_ligatures"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024verticalWidths",
            "name": "verticalWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_verticalWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024underlinePosition",
            "name": "underlinePosition",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_underlinePosition"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024underlineThickness",
            "name": "underlineThickness",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_underlineThickness"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\FontFaceData\u003A\u003A\u0024mathTable",
            "name": "mathTable",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-FontFaceData.html#property_mathTable"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\GsubParser",
            "name": "GsubParser",
            "summary": "Parses\u0020GSUB\u0020\u0028Glyph\u0020Substitution\u0029\u0020table\u0020for\u0020ligature\u0020features.",
            "url": "classes/Phpdftk-FontParser-GsubParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\GsubParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-GsubParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\KerningParser",
            "name": "KerningParser",
            "summary": "Parses\u0020kerning\u0020data\u0020from\u0020GPOS\u0020table\u0020\u0028or\u0020legacy\u0020kern\u0020table\u0029.",
            "url": "classes/Phpdftk-FontParser-KerningParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\KerningParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-KerningParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants",
            "name": "MathConstants",
            "summary": "Parsed\u0020MathConstants\u0020sub\u002Dtable\u0020from\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024scriptPercentScaleDown",
            "name": "scriptPercentScaleDown",
            "summary": "Percent\u0020scale\u002Ddown\u0020for\u0020script\u002Dlevel\u0020glyphs\u0020\u0028e.g.\u002070\u0020\u003D\u003E\u002070\u0025\u0029.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_scriptPercentScaleDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024scriptScriptPercentScaleDown",
            "name": "scriptScriptPercentScaleDown",
            "summary": "Percent\u0020scale\u002Ddown\u0020for\u0020script\u002Dscript\u002Dlevel\u0020glyphs\u0020\u0028e.g.\u002055\u0029.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_scriptScriptPercentScaleDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024delimitedSubFormulaMinHeight",
            "name": "delimitedSubFormulaMinHeight",
            "summary": "Minimum\u0020height\u0020\u0028in\u0020design\u0020units\u0029\u0020at\u0020which\u0020a\u0020delimiter\u0020is\n\u0020drawn\u0020as\u0020the\u0020next\u0020stretched\u0020variant.\u0020Used\u0020by\u0020stretchy\n\u0020brackets\u0020and\u0020radicals.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_delimitedSubFormulaMinHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024displayOperatorMinHeight",
            "name": "displayOperatorMinHeight",
            "summary": "Minimum\u0020height\u0020\u0028design\u0020units\u0029\u0020at\u0020which\u0020an\u0020operator\u0020switches\n\u0020to\u0020its\u0020display\u0020\u0028large\u0029\u0020form.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_displayOperatorMinHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024mathLeading",
            "name": "mathLeading",
            "summary": "Recommended\u0020gap\u0020between\u0020top\u0020of\u0020a\u0020math\u0020row\u0020and\u0020the\u0020top\u0020of\n\u0020its\u0020tallest\u0020glyph.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_mathLeading"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024axisHeight",
            "name": "axisHeight",
            "summary": "Vertical\u0020position\u0020of\u0020the\u0020mathematical\u0020axis\u0020\u0028the\u0020centerline\n\u0020for\u0020fraction\u0020bars,\u0020sum\u0020operators,\u0020etc.\u0029\u0020above\u0020baseline.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_axisHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024accentBaseHeight",
            "name": "accentBaseHeight",
            "summary": "Vertical\u0020alignment\u0020for\u0020an\u0020accent\u0027s\u0020bottom\u0020relative\u0020to\u0020the\n\u0020base\u0020glyph\u0027s\u0020top.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_accentBaseHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024flattenedAccentBaseHeight",
            "name": "flattenedAccentBaseHeight",
            "summary": "Vertical\u0020alignment\u0020for\u0020a\u0020flattened\u0020accent\u0027s\u0020bottom.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_flattenedAccentBaseHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024subscriptShiftDown",
            "name": "subscriptShiftDown",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_subscriptShiftDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024subscriptTopMax",
            "name": "subscriptTopMax",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_subscriptTopMax"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024subscriptBaselineDropMin",
            "name": "subscriptBaselineDropMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_subscriptBaselineDropMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024superscriptShiftUp",
            "name": "superscriptShiftUp",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_superscriptShiftUp"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024superscriptShiftUpCramped",
            "name": "superscriptShiftUpCramped",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_superscriptShiftUpCramped"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024superscriptBottomMin",
            "name": "superscriptBottomMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_superscriptBottomMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024superscriptBaselineDropMax",
            "name": "superscriptBaselineDropMax",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_superscriptBaselineDropMax"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024subSuperscriptGapMin",
            "name": "subSuperscriptGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_subSuperscriptGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024superscriptBottomMaxWithSubscript",
            "name": "superscriptBottomMaxWithSubscript",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_superscriptBottomMaxWithSubscript"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024spaceAfterScript",
            "name": "spaceAfterScript",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_spaceAfterScript"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024upperLimitGapMin",
            "name": "upperLimitGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_upperLimitGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024upperLimitBaselineRiseMin",
            "name": "upperLimitBaselineRiseMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_upperLimitBaselineRiseMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024lowerLimitGapMin",
            "name": "lowerLimitGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_lowerLimitGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024lowerLimitBaselineDropMin",
            "name": "lowerLimitBaselineDropMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_lowerLimitBaselineDropMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stackTopShiftUp",
            "name": "stackTopShiftUp",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stackTopShiftUp"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stackTopDisplayStyleShiftUp",
            "name": "stackTopDisplayStyleShiftUp",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stackTopDisplayStyleShiftUp"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stackBottomShiftDown",
            "name": "stackBottomShiftDown",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stackBottomShiftDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stackBottomDisplayStyleShiftDown",
            "name": "stackBottomDisplayStyleShiftDown",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stackBottomDisplayStyleShiftDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stackGapMin",
            "name": "stackGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stackGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stackDisplayStyleGapMin",
            "name": "stackDisplayStyleGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stackDisplayStyleGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stretchStackTopShiftUp",
            "name": "stretchStackTopShiftUp",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stretchStackTopShiftUp"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stretchStackBottomShiftDown",
            "name": "stretchStackBottomShiftDown",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stretchStackBottomShiftDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stretchStackGapAboveMin",
            "name": "stretchStackGapAboveMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stretchStackGapAboveMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024stretchStackGapBelowMin",
            "name": "stretchStackGapBelowMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_stretchStackGapBelowMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionNumeratorShiftUp",
            "name": "fractionNumeratorShiftUp",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionNumeratorShiftUp"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionNumeratorDisplayStyleShiftUp",
            "name": "fractionNumeratorDisplayStyleShiftUp",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionNumeratorDisplayStyleShiftUp"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionDenominatorShiftDown",
            "name": "fractionDenominatorShiftDown",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionDenominatorShiftDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionDenominatorDisplayStyleShiftDown",
            "name": "fractionDenominatorDisplayStyleShiftDown",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionDenominatorDisplayStyleShiftDown"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionNumeratorGapMin",
            "name": "fractionNumeratorGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionNumeratorGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionNumDisplayStyleGapMin",
            "name": "fractionNumDisplayStyleGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionNumDisplayStyleGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionRuleThickness",
            "name": "fractionRuleThickness",
            "summary": "Thickness\u0020of\u0020the\u0020horizontal\u0020bar\u0020in\u0020fractions.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionRuleThickness"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionDenominatorGapMin",
            "name": "fractionDenominatorGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionDenominatorGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024fractionDenomDisplayStyleGapMin",
            "name": "fractionDenomDisplayStyleGapMin",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_fractionDenomDisplayStyleGapMin"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024skewedFractionHorizontalGap",
            "name": "skewedFractionHorizontalGap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_skewedFractionHorizontalGap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024skewedFractionVerticalGap",
            "name": "skewedFractionVerticalGap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_skewedFractionVerticalGap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024overbarVerticalGap",
            "name": "overbarVerticalGap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_overbarVerticalGap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024overbarRuleThickness",
            "name": "overbarRuleThickness",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_overbarRuleThickness"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024overbarExtraAscender",
            "name": "overbarExtraAscender",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_overbarExtraAscender"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024underbarVerticalGap",
            "name": "underbarVerticalGap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_underbarVerticalGap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024underbarRuleThickness",
            "name": "underbarRuleThickness",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_underbarRuleThickness"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024underbarExtraDescender",
            "name": "underbarExtraDescender",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_underbarExtraDescender"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalVerticalGap",
            "name": "radicalVerticalGap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalVerticalGap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalDisplayStyleVerticalGap",
            "name": "radicalDisplayStyleVerticalGap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalDisplayStyleVerticalGap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalRuleThickness",
            "name": "radicalRuleThickness",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalRuleThickness"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalExtraAscender",
            "name": "radicalExtraAscender",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalExtraAscender"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalKernBeforeDegree",
            "name": "radicalKernBeforeDegree",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalKernBeforeDegree"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalKernAfterDegree",
            "name": "radicalKernAfterDegree",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalKernAfterDegree"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstants\u003A\u003A\u0024radicalDegreeBottomRaisePercent",
            "name": "radicalDegreeBottomRaisePercent",
            "summary": "Percent\u0020of\u0020radical\u0020sign\u0020height\u0020the\u0020degree\u0020base\u0020rises\u0020\u0028e.g.\u002060\u0029.",
            "url": "classes/Phpdftk-FontParser-MathConstants.html#property_radicalDegreeBottomRaisePercent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstantsParser",
            "name": "MathConstantsParser",
            "summary": "Parser\u0020for\u0020the\u0020MathConstants\u0020sub\u002Dtable\u0020of\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathConstantsParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathConstantsParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathConstantsParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphAssembly",
            "name": "MathGlyphAssembly",
            "summary": "Recipe\u0020for\u0020building\u0020a\u0020stretchy\u0020delimiter\u0020from\u0020glyph\u0020parts.",
            "url": "classes/Phpdftk-FontParser-MathGlyphAssembly.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphAssembly\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphAssembly.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphAssembly\u003A\u003A\u0024italicsCorrection",
            "name": "italicsCorrection",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphAssembly.html#property_italicsCorrection"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphAssembly\u003A\u003A\u0024parts",
            "name": "parts",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphAssembly.html#property_parts"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphConstruction",
            "name": "MathGlyphConstruction",
            "summary": "One\u0020stretchy\u0020delimiter\u0020recipe\u0020from\u0020a\u0020\u007B\u0040see\u0020MathVariants\u007D\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathGlyphConstruction.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphConstruction\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphConstruction.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphConstruction\u003A\u003A\u0024variants",
            "name": "variants",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphConstruction.html#property_variants"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphConstruction\u003A\u003A\u0024assembly",
            "name": "assembly",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphConstruction.html#property_assembly"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfo",
            "name": "MathGlyphInfo",
            "summary": "Parsed\u0020MathGlyphInfo\u0020sub\u002Dtable\u0020from\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfo.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfo.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfo\u003A\u003A\u0024italicCorrections",
            "name": "italicCorrections",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfo.html#property_italicCorrections"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfo\u003A\u003A\u0024topAccentAttachments",
            "name": "topAccentAttachments",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfo.html#property_topAccentAttachments"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfo\u003A\u003A\u0024extendedShapes",
            "name": "extendedShapes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfo.html#property_extendedShapes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfo\u003A\u003A\u0024kernInfoBytes",
            "name": "kernInfoBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfo.html#property_kernInfoBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfoParser",
            "name": "MathGlyphInfoParser",
            "summary": "Parser\u0020for\u0020the\u0020MathGlyphInfo\u0020sub\u002Dtable\u0020of\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfoParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathGlyphInfoParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathGlyphInfoParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKern",
            "name": "MathKern",
            "summary": "One\u0020corner\u0020kern\u0020table\u0020from\u0020a\u0020\u007B\u0040see\u0020MathKernRecord\u007D.",
            "url": "classes/Phpdftk-FontParser-MathKern.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKern\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKern.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKern\u003A\u003AvalueAt\u0028\u0029",
            "name": "valueAt",
            "summary": "Look\u0020up\u0020the\u0020kern\u0020value\u0020for\u0020a\u0020given\u0020Y\u0020offset\u0020above\u0020baseline.",
            "url": "classes/Phpdftk-FontParser-MathKern.html#method_valueAt"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKern\u003A\u003A\u0024correctionHeights",
            "name": "correctionHeights",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKern.html#property_correctionHeights"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKern\u003A\u003A\u0024kernValues",
            "name": "kernValues",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKern.html#property_kernValues"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernInfo",
            "name": "MathKernInfo",
            "summary": "Parsed\u0020MathKernInfo\u0020sub\u002Dtable\u0020from\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathKernInfo.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernInfo.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernInfo\u003A\u003A\u0024records",
            "name": "records",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernInfo.html#property_records"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernInfoParser",
            "name": "MathKernInfoParser",
            "summary": "Parser\u0020for\u0020the\u0020MathKernInfo\u0020sub\u002Dtable\u0020of\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathKernInfoParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernInfoParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernInfoParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernRecord",
            "name": "MathKernRecord",
            "summary": "Per\u002Dglyph\u0020corner\u0020kern\u0020table.\u0020Up\u0020to\u0020four\u0020corner\u002Dspecific\u0020kern\ntables\u003B\u0020each\u0020corner\u0020is\u0020null\u0020when\u0020the\u0020font\u0020supplies\u0020no\u0020kerning\nfor\u0020that\u0020corner.",
            "url": "classes/Phpdftk-FontParser-MathKernRecord.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernRecord\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernRecord.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernRecord\u003A\u003A\u0024topRight",
            "name": "topRight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernRecord.html#property_topRight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernRecord\u003A\u003A\u0024topLeft",
            "name": "topLeft",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernRecord.html#property_topLeft"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernRecord\u003A\u003A\u0024bottomRight",
            "name": "bottomRight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernRecord.html#property_bottomRight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathKernRecord\u003A\u003A\u0024bottomLeft",
            "name": "bottomLeft",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathKernRecord.html#property_bottomLeft"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData",
            "name": "MathTableData",
            "summary": "Parsed\u0020\u0060MATH\u0060\u0020table\u0020from\u0020an\u0020OpenType\u0020math\u0020font\u0020\u0028Latin\u0020Modern\u0020Math,\nSTIX\u0020Two\u0020Math,\u0020Cambria\u0020Math,\u0020...\u0029.\u0020Defined\u0020in\u0020the\u0020OpenType\u0020spec\nhttps\u003A\/\/learn.microsoft.com\/en\u002Dus\/typography\/opentype\/spec\/math.",
            "url": "classes/Phpdftk-FontParser-MathTableData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003AhasMathConstants\u0028\u0029",
            "name": "hasMathConstants",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method_hasMathConstants"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003AhasMathGlyphInfo\u0028\u0029",
            "name": "hasMathGlyphInfo",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method_hasMathGlyphInfo"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003AhasMathVariants\u0028\u0029",
            "name": "hasMathVariants",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#method_hasMathVariants"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024majorVersion",
            "name": "majorVersion",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_majorVersion"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024minorVersion",
            "name": "minorVersion",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_minorVersion"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024mathConstantsBytes",
            "name": "mathConstantsBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_mathConstantsBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024mathGlyphInfoBytes",
            "name": "mathGlyphInfoBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_mathGlyphInfoBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathTableData\u003A\u003A\u0024mathVariantsBytes",
            "name": "mathVariantsBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathTableData.html#property_mathVariantsBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariants",
            "name": "MathVariants",
            "summary": "Parsed\u0020MathVariants\u0020sub\u002Dtable\u0020from\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathVariants.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariants\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathVariants.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariants\u003A\u003A\u0024minConnectorOverlap",
            "name": "minConnectorOverlap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathVariants.html#property_minConnectorOverlap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariants\u003A\u003A\u0024verticalConstructions",
            "name": "verticalConstructions",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathVariants.html#property_verticalConstructions"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariants\u003A\u003A\u0024horizontalConstructions",
            "name": "horizontalConstructions",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathVariants.html#property_horizontalConstructions"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariantsParser",
            "name": "MathVariantsParser",
            "summary": "Parser\u0020for\u0020the\u0020MathVariants\u0020sub\u002Dtable\u0020of\u0020an\u0020OpenType\u0020MATH\u0020table.",
            "url": "classes/Phpdftk-FontParser-MathVariantsParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\MathVariantsParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-MathVariantsParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData",
            "name": "OpenTypeData",
            "summary": "Parsed\u0020OpenType\u0020CFF\u0020font\u0020data\u0020\u2014\u0020metrics,\u0020glyph\u0020widths,\u0020and\u0020raw\u0020CFF\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeData\u003A\u003A\u0024cffBytes",
            "name": "cffBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeData.html#property_cffBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser",
            "name": "OpenTypeParser",
            "summary": "Parser\u0020for\u0020OpenType\u0020fonts\u0020with\u0020CFF\u0020outlines\u0020\u0028sfVersion\u0020\u0022OTTO\u0022\u0029.",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Create\u0020a\u0020parser\u0020from\u0020raw\u0020font\u0020bytes\u0020instead\u0020of\u0020a\u0020file\u0020path.",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html#method_fromBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\OpenTypeParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-OpenTypeParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TextShaper",
            "name": "TextShaper",
            "summary": "Simple\u0020text\u0020shaper\u0020for\u0020Latin\u0020ligature\u0020substitution.",
            "url": "classes/Phpdftk-FontParser-TextShaper.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TextShaper\u003A\u003AapplyLigatures\u0028\u0029",
            "name": "applyLigatures",
            "summary": "Apply\u0020ligature\u0020substitutions\u0020to\u0020a\u0020GID\u0020sequence.",
            "url": "classes/Phpdftk-FontParser-TextShaper.html#method_applyLigatures"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData",
            "name": "TrueTypeData",
            "summary": "Common\u0020shape\u0020for\u0020a\u0020parsed\u0020font\u0020face\u0020\u2014\u0020the\u0020fields\u0020any\u0020downstream\nconsumer\u0020needs\u0020to\u0020lay\u0020out,\u0020shape,\u0020and\u0020embed\u0020text.",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024isVariableFont",
            "name": "isVariableFont",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_isVariableFont"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024variationAxes",
            "name": "variationAxes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_variationAxes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeData\u003A\u003A\u0024namedInstances",
            "name": "namedInstances",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeData.html#property_namedInstances"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser",
            "name": "TrueTypeParser",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Create\u0020a\u0020parser\u0020from\u0020raw\u0020font\u0020bytes\u0020instead\u0020of\u0020a\u0020file\u0020path.",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html#method_fromBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeSubsetter",
            "name": "TrueTypeSubsetter",
            "summary": "Produces\u0020a\u0020minimal\u0020valid\u0020TrueType\u0020font\u0020containing\u0020only\u0020requested\u0020glyphs.",
            "url": "classes/Phpdftk-FontParser-TrueTypeSubsetter.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeSubsetter\u003A\u003Asubset\u0028\u0029",
            "name": "subset",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-TrueTypeSubsetter.html#method_subset"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\TrueTypeSubsetter\u003A\u003AgetGidMap\u0028\u0029",
            "name": "getGidMap",
            "summary": "The\u0020old\u0020\u2192\u0020new\u0020GID\u0020map\u0020from\u0020the\u0020most\u0020recent\u0020\u0060subset\u0028\u0029\u0060\u0020call.\u0020Returns\nan\u0020empty\u0020array\u0020if\u0020\u0060subset\u0028\u0029\u0060\u0020has\u0020not\u0020been\u0020called\u0020yet.\u0020Callers\u0020use\u0020this\nto\u0020translate\u0020any\u0020pre\u002Dsubset\u0020GIDs\u0020they\u0020hold\u0020into\u0020the\u0020renumbered\u0020GIDs\nthat\u0020live\u0020in\u0020the\u0020emitted\u0020subset\u0020font.",
            "url": "classes/Phpdftk-FontParser-TrueTypeSubsetter.html#method_getGidMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data",
            "name": "Type1Data",
            "summary": "Parsed\u0020data\u0020from\u0020a\u0020Type\u00201\u0020font\u0020\u0028PFB\/PFA\u0029.",
            "url": "classes/Phpdftk-FontParser-Type1Data.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024postScriptName",
            "name": "postScriptName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_postScriptName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024familyName",
            "name": "familyName",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_familyName"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024ascent",
            "name": "ascent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_ascent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024descent",
            "name": "descent",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_descent"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024capHeight",
            "name": "capHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_capHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024xHeight",
            "name": "xHeight",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_xHeight"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024italicAngle",
            "name": "italicAngle",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_italicAngle"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024stemV",
            "name": "stemV",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_stemV"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024flags",
            "name": "flags",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_flags"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024fontBBox",
            "name": "fontBBox",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_fontBBox"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024charWidths",
            "name": "charWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_charWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024unicodeMap",
            "name": "unicodeMap",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_unicodeMap"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024fontBytes",
            "name": "fontBytes",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_fontBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024length1",
            "name": "length1",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_length1"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024length2",
            "name": "length2",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_length2"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024length3",
            "name": "length3",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_length3"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024glyphWidths",
            "name": "glyphWidths",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_glyphWidths"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Data\u003A\u003A\u0024encoding",
            "name": "encoding",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Data.html#property_encoding"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser",
            "name": "Type1Parser",
            "summary": "Parses\u0020Type\u00201\u0020font\u0020files\u0020\u0028PFB\u0020binary\u0020and\u0020PFA\u0020ASCII\u0020formats\u0029.",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Create\u0020a\u0020parser\u0020from\u0020raw\u0020font\u0020bytes\u0020instead\u0020of\u0020a\u0020file\u0020path.",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html#method_fromBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Type1Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-FontParser-Type1Parser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser",
            "name": "Woff2Parser",
            "summary": "WOFF\u00202.0\u0020\u0028Web\u0020Open\u0020Font\u0020Format\u00202.0\u0029\u0020decompressor.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003Adecompress\u0028\u0029",
            "name": "decompress",
            "summary": "Decompress\u0020a\u0020WOFF2\u0020file\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_decompress"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003AdecompressBytes\u0028\u0029",
            "name": "decompressBytes",
            "summary": "Decompress\u0020WOFF2\u0020bytes\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_decompressBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003AisWoff2\u0028\u0029",
            "name": "isWoff2",
            "summary": "Detect\u0020whether\u0020bytes\u0020are\u0020a\u0020WOFF2\u0020file.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_isWoff2"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\Woff2Parser\u003A\u003AdetectFlavor\u0028\u0029",
            "name": "detectFlavor",
            "summary": "Detect\u0020the\u0020flavor\u0020\u0028TrueType\u0020or\u0020OpenType\u0020CFF\u0029\u0020of\u0020a\u0020WOFF2\u0020file.",
            "url": "classes/Phpdftk-FontParser-Woff2Parser.html#method_detectFlavor"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser",
            "name": "WoffParser",
            "summary": "WOFF\u0020\u0028Web\u0020Open\u0020Font\u0020Format\u00201.0\u0029\u0020decompressor.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003Adecompress\u0028\u0029",
            "name": "decompress",
            "summary": "Decompress\u0020a\u0020WOFF\u0020file\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_decompress"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003AdecompressBytes\u0028\u0029",
            "name": "decompressBytes",
            "summary": "Decompress\u0020WOFF\u0020bytes\u0020to\u0020raw\u0020sfnt\u0020\u0028TTF\/OTF\u0029\u0020bytes.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_decompressBytes"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003AisWoff\u0028\u0029",
            "name": "isWoff",
            "summary": "Detect\u0020whether\u0020bytes\u0020are\u0020a\u0020WOFF\u0020file.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_isWoff"
        },                {
            "fqsen": "\\Phpdftk\\FontParser\\WoffParser\u003A\u003AdetectFlavor\u0028\u0029",
            "name": "detectFlavor",
            "summary": "Detect\u0020the\u0020flavor\u0020\u0028TrueType\u0020or\u0020OpenType\u0020CFF\u0029\u0020of\u0020a\u0020WOFF\u0020file.",
            "url": "classes/Phpdftk-FontParser-WoffParser.html#method_detectFlavor"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\FontParser",
            "name": "FontParser",
            "summary": "",
            "url": "namespaces/phpdftk-fontparser.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
