Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Exception\\InvalidPdfException",
            "name": "InvalidPdfException",
            "summary": "Thrown\u0020when\u0020the\u0020parser\u0020encounters\u0020structurally\u0020invalid\u0020PDF\u0020data\u0020that\ncannot\u0020be\u0020recovered\u0020\u0028e.g.\u0020missing\u0020\u0025PDF\u0020header,\u0020corrupt\u0020xref\u0020table,\nunresolvable\u0020\/Root\u0020catalog\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-Exception-InvalidPdfException.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Exception\\UnsupportedFilterException",
            "name": "UnsupportedFilterException",
            "summary": "Thrown\u0020when\u0020a\u0020stream\u0020uses\u0020a\u0020filter\u0020the\u0020reader\u0020cannot\u0020decode\n\u0028e.g.\u0020JBIG2\u0020without\u0020the\u0020jbig2dec\u0020extension,\u0020or\u0020an\u0020unrecognized\ncustom\u0020filter\u0020name\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-Exception-UnsupportedFilterException.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver",
            "name": "ObjectResolver",
            "summary": "Lazy\u002Dloading\u0020object\u0020cache.\u0020Resolves\u0020indirect\u0020references\u0020by\u0020seeking\nto\u0020the\u0020xref\u002Drecorded\u0020byte\u0020offset,\u0020parsing\u0020the\u0020object,\u0020decompressing\nany\u0020stream\u0020data,\u0020and\u0020caching\u0020the\u0020result.",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003AmergeOlderEntries\u0028\u0029",
            "name": "mergeOlderEntries",
            "summary": "Merge\u0020additional\u0020xref\u0020entries\u0020\u0028older\u0020entries\u0020do\u0020NOT\u0020overwrite\nnewer\u0020ones\u0020\u2014\u0020newer\u0020entries\u0020from\u0020later\u0020xref\u0020sections\u0020take\nprecedence\u0029.\u0020Used\u0020for\u0020\u0060\/Prev\u0060\u0020chain\u0020following.",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_mergeOlderEntries"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_resolve"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003AresolveReference\u0028\u0029",
            "name": "resolveReference",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_resolveReference"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_has"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003AgetEntry\u0028\u0029",
            "name": "getEntry",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_getEntry"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003AgetObjectNumbers\u0028\u0029",
            "name": "getObjectNumbers",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_getObjectNumbers"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\ObjectResolver\u003A\u003AgetEntries\u0028\u0029",
            "name": "getEntries",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-ObjectResolver.html#method_getEntries"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\BitReader",
            "name": "BitReader",
            "summary": "Reads\u0020variable\u002Dwidth\u0020bit\u0020fields\u0020from\u0020a\u0020binary\u0020buffer.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-BitReader.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\BitReader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-BitReader.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\BitReader\u003A\u003AreadBits\u0028\u0029",
            "name": "readBits",
            "summary": "Read\u0020an\u0020unsigned\u0020integer\u0020of\u0020the\u0020given\u0020bit\u0020width.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-BitReader.html#method_readBits"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\BitReader\u003A\u003AalignToByte\u0028\u0029",
            "name": "alignToByte",
            "summary": "Advance\u0020to\u0020the\u0020next\u0020byte\u0020boundary.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-BitReader.html#method_alignToByte"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\BitReader\u003A\u003AgetBitPosition\u0028\u0029",
            "name": "getBitPosition",
            "summary": "Current\u0020position\u0020in\u0020bits.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-BitReader.html#method_getBitPosition"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\BitReader\u003A\u003AgetBytePosition\u0028\u0029",
            "name": "getBytePosition",
            "summary": "Current\u0020position\u0020in\u0020bytes\u0020\u0028rounded\u0020down\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-BitReader.html#method_getBytePosition"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ContentStreamOp",
            "name": "ContentStreamOp",
            "summary": "A\u0020single\u0020content\u0020stream\u0020operation\u003A\u0020zero\u0020or\u0020more\u0020operands\u0020followed\nby\u0020an\u0020operator\u0020keyword.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ContentStreamOp.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ContentStreamOp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ContentStreamOp.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ContentStreamOp\u003A\u003A\u0024operands",
            "name": "operands",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ContentStreamOp.html#property_operands"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ContentStreamOp\u003A\u003A\u0024operator",
            "name": "operator",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ContentStreamOp.html#property_operator"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ContentStreamParser",
            "name": "ContentStreamParser",
            "summary": "Parses\u0020decoded\u0020content\u0020stream\u0020data\u0020into\u0020a\u0020sequence\u0020of\u0020operations.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ContentStreamParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ContentStreamParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse\u0020content\u0020stream\u0020data\u0020into\u0020operations.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ContentStreamParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\HintTableParser",
            "name": "HintTableParser",
            "summary": "Parses\u0020the\u0020binary\u0020hint\u0020table\u0020data\u0020from\u0020linearized\u0020PDF\u0020hint\u0020streams.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-HintTableParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\HintTableParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-HintTableParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\HintTableParser\u003A\u003AparsePageOffsetTable\u0028\u0029",
            "name": "parsePageOffsetTable",
            "summary": "Parse\u0020the\u0020page\u0020offset\u0020hint\u0020table\u0020starting\u0020at\u0020the\u0020given\u0020byte\u0020offset.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-HintTableParser.html#method_parsePageOffsetTable"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\HintTableParser\u003A\u003AparseSharedObjectTable\u0028\u0029",
            "name": "parseSharedObjectTable",
            "summary": "Parse\u0020the\u0020shared\u0020object\u0020hint\u0020table\u0020starting\u0020at\u0020the\u0020given\u0020byte\u0020offset.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-HintTableParser.html#method_parseSharedObjectTable"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectParser",
            "name": "ObjectParser",
            "summary": "Recursive\u002Ddescent\u0020PDF\u0020object\u0020parser.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectParser\u003A\u003AparseValue\u0028\u0029",
            "name": "parseValue",
            "summary": "Parse\u0020any\u0020PDF\u0020value.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectParser.html#method_parseValue"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectParser\u003A\u003AparseIndirectObject\u0028\u0029",
            "name": "parseIndirectObject",
            "summary": "Parse\u0020a\u0020complete\u0020indirect\u0020object\u003A\u0020\u0060X\u0020Y\u0020obj\u0020\u003Cvalue\u003E\u0020endobj\u0060.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectParser.html#method_parseIndirectObject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectScanner",
            "name": "ObjectScanner",
            "summary": "Scans\u0020raw\u0020PDF\u0020bytes\u0020for\u0020indirect\u0020object\u0020definitions\u0020to\u0020reconstruct\na\u0020cross\u002Dreference\u0020table\u0020when\u0020the\u0020normal\u0020xref\u0020is\u0020corrupted.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectScanner.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectScanner\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "Scan\u0020the\u0020PDF\u0020bytes\u0020for\u0020all\u0020\u0060N\u0020M\u0020obj\u0060\u0020patterns.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectScanner.html#method_scan"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectStreamParser",
            "name": "ObjectStreamParser",
            "summary": "Unpacks\u0020objects\u0020stored\u0020inside\u0020a\u0020\/Type\u0020\/ObjStm\u0020stream\u0020\u2014\nISO\u002032000\u002D2\u0020\u00A77.5.7.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectStreamParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectStreamParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectStreamParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\ObjectStreamParser\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020all\u0020objects\u0020from\u0020an\u0020ObjStm.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-ObjectStreamParser.html#method_unpack"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry",
            "name": "PageHintEntry",
            "summary": "A\u0020single\u0020entry\u0020from\u0020the\u0020page\u0020offset\u0020hint\u0020table\u0020\u2014\u0020ISO\u002032000\u002D2\u0020\u00A7F.4.1.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024objectCountDelta",
            "name": "objectCountDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_objectCountDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024pageLengthDelta",
            "name": "pageLengthDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_pageLengthDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024sharedRefCountDelta",
            "name": "sharedRefCountDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_sharedRefCountDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024sharedObjIds",
            "name": "sharedObjIds",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_sharedObjIds"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024sharedObjNumeratorDelta",
            "name": "sharedObjNumeratorDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_sharedObjNumeratorDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024contentStreamOffsetDelta",
            "name": "contentStreamOffsetDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_contentStreamOffsetDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageHintEntry\u003A\u003A\u0024contentStreamLengthDelta",
            "name": "contentStreamLengthDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageHintEntry.html#property_contentStreamLengthDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable",
            "name": "PageOffsetHintTable",
            "summary": "Parsed\u0020page\u0020offset\u0020hint\u0020table\u0020\u2014\u0020ISO\u002032000\u002D2\u0020\u00A7F.4.1.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003AgetPageByteRange\u0028\u0029",
            "name": "getPageByteRange",
            "summary": "Compute\u0020the\u0020byte\u0020offset\u0020and\u0020length\u0020for\u0020a\u0020page\u0020\u00280\u002Dindexed\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#method_getPageByteRange"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024minObjectsPerPage",
            "name": "minObjectsPerPage",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_minObjectsPerPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024firstPageLocation",
            "name": "firstPageLocation",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_firstPageLocation"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024minPageLength",
            "name": "minPageLength",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_minPageLength"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024minSharedRefsPerPage",
            "name": "minSharedRefsPerPage",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_minSharedRefsPerPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024minSharedObjId",
            "name": "minSharedObjId",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_minSharedObjId"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024minContentStreamOffset",
            "name": "minContentStreamOffset",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_minContentStreamOffset"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024minContentStreamLength",
            "name": "minContentStreamLength",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_minContentStreamLength"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\PageOffsetHintTable\u003A\u003A\u0024entries",
            "name": "entries",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-PageOffsetHintTable.html#property_entries"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintEntry",
            "name": "SharedObjectHintEntry",
            "summary": "A\u0020single\u0020entry\u0020from\u0020the\u0020shared\u0020object\u0020hint\u0020table\u0020\u2014\u0020ISO\u002032000\u002D2\u0020\u00A7F.4.2.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintEntry.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintEntry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintEntry.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintEntry\u003A\u003A\u0024lengthDelta",
            "name": "lengthDelta",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintEntry.html#property_lengthDelta"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintEntry\u003A\u003A\u0024isSignatureObject",
            "name": "isSignatureObject",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintEntry.html#property_isSignatureObject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintEntry\u003A\u003A\u0024numObjects",
            "name": "numObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintEntry.html#property_numObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable",
            "name": "SharedObjectHintTable",
            "summary": "Parsed\u0020shared\u0020object\u0020hint\u0020table\u0020\u2014\u0020ISO\u002032000\u002D2\u0020\u00A7F.4.2.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable\u003A\u003A\u0024firstSharedObjNumber",
            "name": "firstSharedObjNumber",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html#property_firstSharedObjNumber"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable\u003A\u003A\u0024firstSharedObjOffset",
            "name": "firstSharedObjOffset",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html#property_firstSharedObjOffset"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable\u003A\u003A\u0024numSharedGroups",
            "name": "numSharedGroups",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html#property_numSharedGroups"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable\u003A\u003A\u0024minGroupLength",
            "name": "minGroupLength",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html#property_minGroupLength"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\SharedObjectHintTable\u003A\u003A\u0024entries",
            "name": "entries",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-SharedObjectHintTable.html#property_entries"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\StreamParser",
            "name": "StreamParser",
            "summary": "Applies\u0020the\u0020filter\u0020pipeline\u0020from\u0020a\u0020stream\u0020dictionary\u0027s\u0020\u0060\/Filter\u0060\nentry\u0020to\u0020decompress\u0020raw\u0020stream\u0020data.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-StreamParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\StreamParser\u003A\u003AsetResolver\u0028\u0029",
            "name": "setResolver",
            "summary": "Set\u0020the\u0020object\u0020resolver\u0020for\u0020resolving\u0020indirect\u0020\/DecodeParms\u0020references.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-StreamParser.html#method_setResolver"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\StreamParser\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decode\u0020stream\u0020data\u0020using\u0020the\u0020filter\u0028s\u0029\u0020declared\u0020in\u0020\u0024dict.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-StreamParser.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\XrefParser",
            "name": "XrefParser",
            "summary": "Parses\u0020a\u0020classic\u0020cross\u002Dreference\u0020table\u0020and\u0020its\u0020trailer\u0020dictionary.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-XrefParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\XrefParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-XrefParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\XrefParser\u003A\u003AparseClassicXref\u0028\u0029",
            "name": "parseClassicXref",
            "summary": "Parse\u0020a\u0020classic\u0020xref\u0020table\u0020at\u0020the\u0020given\u0020byte\u0020offset.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-XrefParser.html#method_parseClassicXref"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\XrefStreamParser",
            "name": "XrefStreamParser",
            "summary": "Parses\u0020a\u0020cross\u002Dreference\u0020stream\u0020\u0028\/Type\u0020\/XRef\u0029\u0020\u2014\u0020ISO\u002032000\u002D2\u0020\u00A77.5.8.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-XrefStreamParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\XrefStreamParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-XrefStreamParser.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser\\XrefStreamParser\u003A\u003AparseXrefStream\u0028\u0029",
            "name": "parseXrefStream",
            "summary": "Parse\u0020a\u0020cross\u002Dreference\u0020stream\u0020at\u0020the\u0020given\u0020byte\u0020offset.",
            "url": "classes/Phpdftk-Pdf-Reader-Parser-XrefStreamParser.html#method_parseXrefStream"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfDecryptor",
            "name": "PdfDecryptor",
            "summary": "Decrypts\u0020PDF\u0020objects\u0020using\u0020the\u0020Standard\u0020security\u0020handler.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfDecryptor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfDecryptor\u003A\u003AfromEncryptDict\u0028\u0029",
            "name": "fromEncryptDict",
            "summary": "Build\u0020a\u0020decryptor\u0020from\u0020the\u0020trailer\u0027s\u0020\/Encrypt\u0020dictionary\u0020and\u0020a\u0020password.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfDecryptor.html#method_fromEncryptDict"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfDecryptor\u003A\u003AdecryptObject\u0028\u0029",
            "name": "decryptObject",
            "summary": "Decrypt\u0020all\u0020string\u0020and\u0020stream\u0020values\u0020within\u0020a\u0020parsed\u0020object.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfDecryptor.html#method_decryptObject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfDecryptor\u003A\u003AfromEncryptDictPublicKey\u0028\u0029",
            "name": "fromEncryptDictPublicKey",
            "summary": "Build\u0020a\u0020decryptor\u0020from\u0020a\u0020public\u002Dkey\u0020\u0028Adobe.PubSec\u0029\u0020encrypt\u0020dictionary.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfDecryptor.html#method_fromEncryptDictPublicKey"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader",
            "name": "PdfReader",
            "summary": "PDF\u0020reader\u0020\u2014\u0020parses\u0020existing\u0020PDF\u0020files\u0020into\u0020the\u0020phpdftk\u0020object\u0020model.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetParseWarnings\u0028\u0029",
            "name": "getParseWarnings",
            "summary": "Return\u0020warnings\u0020accumulated\u0020during\u0020parsing.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getParseWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AfromFile\u0028\u0029",
            "name": "fromFile",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_fromFile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AfromString\u0028\u0029",
            "name": "fromString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_fromString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AfromFilePublicKey\u0028\u0029",
            "name": "fromFilePublicKey",
            "summary": "Read\u0020a\u0020public\u002Dkey\u0020\u0028certificate\u002Dbased\u0029\u0020encrypted\u0020PDF\u0020from\u0020a\u0020file.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_fromFilePublicKey"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AfromStringPublicKey\u0028\u0029",
            "name": "fromStringPublicKey",
            "summary": "Read\u0020a\u0020public\u002Dkey\u0020\u0028certificate\u002Dbased\u0029\u0020encrypted\u0020PDF\u0020from\u0020a\u0020string.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_fromStringPublicKey"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AfromStream\u0028\u0029",
            "name": "fromStream",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_fromStream"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "PDF\u0020version\u0020string,\u0020e.g.\u0020\u00221.7\u0022.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "Typed\u0020PDF\u0020version\u0020from\u0020the\u0020file\u0020header.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetEffectiveVersion\u0028\u0029",
            "name": "getEffectiveVersion",
            "summary": "Effective\u0020PDF\u0020version\u0020\u2014\u0020max\u0028header,\u0020catalog\u0020\/Version\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getEffectiveVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AvalidateVersion\u0028\u0029",
            "name": "validateVersion",
            "summary": "Scan\u0020the\u0020document\u0020for\u0020structural\u0020features\u0020inconsistent\u0020with\u0020the\ndeclared\u0020version.\u0020Returns\u0020a\u0020list\u0020of\u0020warning\u0020strings.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_validateVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AisLinearized\u0028\u0029",
            "name": "isLinearized",
            "summary": "Check\u0020whether\u0020this\u0020PDF\u0020is\u0020linearized\u0020\u0028web\u002Doptimized\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_isLinearized"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetLinearizationParameters\u0028\u0029",
            "name": "getLinearizationParameters",
            "summary": "Get\u0020linearization\u0020parameters\u0020if\u0020the\u0020PDF\u0020is\u0020linearized.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getLinearizationParameters"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetPageOffsetHintTable\u0028\u0029",
            "name": "getPageOffsetHintTable",
            "summary": "Parse\u0020the\u0020page\u0020offset\u0020hint\u0020table\u0020from\u0020a\u0020linearized\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getPageOffsetHintTable"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetPageByteRange\u0028\u0029",
            "name": "getPageByteRange",
            "summary": "Calculate\u0020the\u0020byte\u0020range\u0020for\u0020a\u0020specific\u0020page\u0020in\u0020a\u0020linearized\u0020PDF.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getPageByteRange"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetTrailer\u0028\u0029",
            "name": "getTrailer",
            "summary": "The\u0020raw\u0020trailer\u0020dictionary.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getTrailer"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetCatalog\u0028\u0029",
            "name": "getCatalog",
            "summary": "Resolve\u0020\/Root\u0020from\u0020the\u0020trailer\u0020\u2014\u0020returns\u0020the\u0020Catalog\u0020dictionary.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getCatalog"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "Resolve\u0020\/Info\u0020from\u0020the\u0020trailer.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getInfo"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetPageCount\u0028\u0029",
            "name": "getPageCount",
            "summary": "Get\u0020the\u0020total\u0020page\u0020count\u0020from\u0020\/Pages\u0020\u002D\u003E\u0020\/Count.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getPageCount"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetPages\u0028\u0029",
            "name": "getPages",
            "summary": "Get\u0020all\u0020Page\u0020dictionaries\u0020by\u0020traversing\u0020the\u0020page\u0020tree.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetPage\u0028\u0029",
            "name": "getPage",
            "summary": "Get\u0020a\u0020specific\u0020page\u0020by\u0020zero\u002Dbased\u0020index.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "Resolve\u0020any\u0020object\u0020by\u0020number.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getObject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AresolveReference\u0028\u0029",
            "name": "resolveReference",
            "summary": "Resolve\u0020an\u0020indirect\u0020reference\u0020to\u0020its\u0020target.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_resolveReference"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetResolver\u0028\u0029",
            "name": "getResolver",
            "summary": "The\u0020underlying\u0020object\u0020resolver.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getResolver"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AextractText\u0028\u0029",
            "name": "extractText",
            "summary": "Extract\u0020text\u0020from\u0020a\u0020page\u0020by\u0020index\u0020\u0028zero\u002Dbased\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_extractText"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AextractAllText\u0028\u0029",
            "name": "extractAllText",
            "summary": "Extract\u0020text\u0020from\u0020all\u0020pages,\u0020concatenated\u0020with\u0020page\u0020separators.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_extractAllText"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AextractTextWithPositions\u0028\u0029",
            "name": "extractTextWithPositions",
            "summary": "Extract\u0020text\u0020with\u0020precise\u0020positioning\u0020from\u0020a\u0020page\u0020by\u0020index\u0020\u0028zero\u002Dbased\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_extractTextWithPositions"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AextractAllTextWithPositions\u0028\u0029",
            "name": "extractAllTextWithPositions",
            "summary": "Extract\u0020text\u0020with\u0020precise\u0020positioning\u0020from\u0020all\u0020pages.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_extractAllTextWithPositions"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetTypedCatalog\u0028\u0029",
            "name": "getTypedCatalog",
            "summary": "Return\u0020the\u0020document\u0020catalog\u0020as\u0020a\u0020typed\u0020Catalog\u0020object.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getTypedCatalog"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetTypedPage\u0028\u0029",
            "name": "getTypedPage",
            "summary": "Return\u0020a\u0020specific\u0020page\u0020as\u0020a\u0020typed\u0020Page\u0020object.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getTypedPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetTypedPages\u0028\u0029",
            "name": "getTypedPages",
            "summary": "Return\u0020all\u0020pages\u0020as\u0020typed\u0020Page\u0020objects.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getTypedPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AgetTypedObject\u0028\u0029",
            "name": "getTypedObject",
            "summary": "Hydrate\u0020any\u0020resolved\u0020object\u0020by\u0020object\u0020number.",
            "url": "classes/Phpdftk-Pdf-Reader-PdfReader.html#method_getTypedObject"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PositionedTextExtractor",
            "name": "PositionedTextExtractor",
            "summary": "Extracts\u0020text\u0020with\u0020precise\u0020positioning\u0020from\u0020a\u0020PDF\u0020page.",
            "url": "classes/Phpdftk-Pdf-Reader-PositionedTextExtractor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PositionedTextExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-PositionedTextExtractor.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\PositionedTextExtractor\u003A\u003AextractFromPage\u0028\u0029",
            "name": "extractFromPage",
            "summary": "Extract\u0020positioned\u0020text\u0020spans\u0020from\u0020a\u0020page\u0020dictionary.",
            "url": "classes/Phpdftk-Pdf-Reader-PositionedTextExtractor.html#method_extractFromPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextExtractor",
            "name": "TextExtractor",
            "summary": "Extracts\u0020text\u0020content\u0020from\u0020a\u0020PDF\u0020page\u0020by\u0020interpreting\u0020content\nstream\u0020operators.",
            "url": "classes/Phpdftk-Pdf-Reader-TextExtractor.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-TextExtractor.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextExtractor\u003A\u003AextractFromPage\u0028\u0029",
            "name": "extractFromPage",
            "summary": "Extract\u0020text\u0020from\u0020a\u0020page\u0020dictionary.",
            "url": "classes/Phpdftk-Pdf-Reader-TextExtractor.html#method_extractFromPage"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan",
            "name": "TextSpan",
            "summary": "A\u0020positioned\u0020span\u0020of\u0020text\u0020extracted\u0020from\u0020a\u0020PDF\u0020page.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024text",
            "name": "text",
            "summary": "The\u0020Unicode\u0020text\u0020content\u0020of\u0020this\u0020span.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_text"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024x",
            "name": "x",
            "summary": "X\u0020coordinate\u0020of\u0020the\u0020span\u0020origin\u0020\u0028left\u0020edge\u0029\u0020in\u0020user\u0020space\u0020points.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_x"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024y",
            "name": "y",
            "summary": "Y\u0020coordinate\u0020of\u0020the\u0020span\u0020baseline\u0020in\u0020user\u0020space\u0020points.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_y"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024width",
            "name": "width",
            "summary": "Width\u0020of\u0020the\u0020span\u0020in\u0020user\u0020space\u0020points.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_width"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024height",
            "name": "height",
            "summary": "Height\u0020of\u0020the\u0020span\u0020in\u0020user\u0020space\u0020points\u0020\u0028based\u0020on\u0020font\u0020size\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_height"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024fontSize",
            "name": "fontSize",
            "summary": "Font\u0020size\u0020in\u0020points\u0020at\u0020the\u0020time\u0020of\u0020rendering.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_fontSize"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\TextSpan\u003A\u003A\u0024fontName",
            "name": "fontName",
            "summary": "PDF\u0020resource\u0020name\u0020of\u0020the\u0020font\u0020\u0028e.g.,\u0020\u0022F1\u0022,\u0020\u0022F2\u0022\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-TextSpan.html#property_fontName"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource",
            "name": "FileSource",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method___destruct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_read"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003AreadByte\u0028\u0029",
            "name": "readByte",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_readByte"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_peek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_seek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003Atell\u0028\u0029",
            "name": "tell",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_tell"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_size"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\FileSource\u003A\u003AisEof\u0028\u0029",
            "name": "isEof",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-FileSource.html#method_isEof"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source",
            "name": "Source",
            "summary": "Seekable\u0020byte\u0020source\u0020abstraction\u0020for\u0020the\u0020PDF\u0020tokenizer.",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_read"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003AreadByte\u0028\u0029",
            "name": "readByte",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_readByte"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_peek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_seek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003Atell\u0028\u0029",
            "name": "tell",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_tell"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_size"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Source\u003A\u003AisEof\u0028\u0029",
            "name": "isEof",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Source.html#method_isEof"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource",
            "name": "StringSource",
            "summary": "Tokenizer\u0020source\u0020backed\u0020by\u0020an\u0020in\u002Dmemory\u0020string\u0020\u002D\u002D\u0020used\u0020by\n\u007B\u0040see\u0020\\Phpdftk\\Pdf\\Reader\\PdfReader\u003A\u003AfromString\u0028\u0029\u007D.",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_read"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003AreadByte\u0028\u0029",
            "name": "readByte",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_readByte"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_peek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_seek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003Atell\u0028\u0029",
            "name": "tell",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_tell"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_size"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\StringSource\u003A\u003AisEof\u0028\u0029",
            "name": "isEof",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-StringSource.html#method_isEof"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Token",
            "name": "Token",
            "summary": "A\u0020single\u0020lexical\u0020token\u0020from\u0020the\u0020PDF\u0020byte\u0020stream,\u0020carrying\u0020its\u0020type,\nstring\u0020value,\u0020and\u0020byte\u0020offset\u0020within\u0020the\u0020source.",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Token.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Token\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Token.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Token\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Token.html#property_type"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Token\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Token.html#property_value"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Token\u003A\u003A\u0024offset",
            "name": "offset",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Token.html#property_offset"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer",
            "name": "Tokenizer",
            "summary": "PDF\u0020tokenizer\u0020\u2014\u0020converts\u0020a\u0020byte\u0020stream\u0020into\u0020a\u0020sequence\u0020of\u0020typed\u0020tokens.",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html#method_getSource"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer\u003A\u003AnextToken\u0028\u0029",
            "name": "nextToken",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html#method_nextToken"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html#method_peek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html#method_seek"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\Tokenizer\u003A\u003Atell\u0028\u0029",
            "name": "tell",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-Tokenizer.html#method_tell"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType",
            "name": "TokenType",
            "summary": "PDF\u0020lexical\u0020token\u0020types\u0020produced\u0020by\u0020the\u0020tokenizer\u0020\u002D\u002D\u0020one\u0020case\u0020per\ndistinct\u0020syntactic\u0020element\u0020in\u0020the\u0020PDF\u0020file\u0020format\u0020\u0028ISO\u002032000\u002D2\u0020S7.2\u0029.",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AName",
            "name": "Name",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Name"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ALiteralString",
            "name": "LiteralString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_LiteralString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AHexString",
            "name": "HexString",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_HexString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AInteger",
            "name": "Integer",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Integer"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AReal",
            "name": "Real",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Real"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ABoolean",
            "name": "Boolean",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Boolean"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ANull",
            "name": "Null",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Null"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AArrayStart",
            "name": "ArrayStart",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_ArrayStart"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AArrayEnd",
            "name": "ArrayEnd",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_ArrayEnd"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ADictStart",
            "name": "DictStart",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_DictStart"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ADictEnd",
            "name": "DictEnd",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_DictEnd"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AStreamKeyword",
            "name": "StreamKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_StreamKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AEndStreamKeyword",
            "name": "EndStreamKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_EndStreamKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AObjKeyword",
            "name": "ObjKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_ObjKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AEndObjKeyword",
            "name": "EndObjKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_EndObjKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ARKeyword",
            "name": "RKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_RKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AXrefKeyword",
            "name": "XrefKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_XrefKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003ATrailerKeyword",
            "name": "TrailerKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_TrailerKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AStartXrefKeyword",
            "name": "StartXrefKeyword",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_StartXrefKeyword"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AUnknown",
            "name": "Unknown",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Unknown"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer\\TokenType\u003A\u003AEof",
            "name": "Eof",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-Tokenizer-TokenType.html#enumcase_Eof"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry",
            "name": "XrefEntry",
            "summary": "A\u0020single\u0020entry\u0020from\u0020the\u0020cross\u002Dreference\u0020table.",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003ATYPE_FREE",
            "name": "TYPE_FREE",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#constant_TYPE_FREE"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003ATYPE_IN_USE",
            "name": "TYPE_IN_USE",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#constant_TYPE_IN_USE"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003ATYPE_COMPRESSED",
            "name": "TYPE_COMPRESSED",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#constant_TYPE_COMPRESSED"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#property_type"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003A\u0024offset",
            "name": "offset",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#property_offset"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\XrefEntry\u003A\u003A\u0024generation",
            "name": "generation",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Reader-XrefEntry.html#property_generation"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-reader-exception.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader",
            "name": "Reader",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-reader.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf",
            "name": "Pdf",
            "summary": "",
            "url": "namespaces/phpdftk-pdf.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-reader-parser.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Reader\\Tokenizer",
            "name": "Tokenizer",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-reader-tokenizer.html"
        }            ]
);
