Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceChecker",
            "name": "ConformanceChecker",
            "summary": "High\u002Dlevel\u0020conformance\u0020checker\u0020for\u0020existing\u0020PDFs.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceChecker.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceChecker\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020a\u0020PDF\u0020file\u0020for\u0020conformance\u0020checking.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceChecker.html#method_open"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceChecker\u003A\u003AopenString\u0028\u0029",
            "name": "openString",
            "summary": "Open\u0020a\u0020PDF\u0020from\u0020a\u0020byte\u0020string\u0020for\u0020conformance\u0020checking.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceChecker.html#method_openString"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceChecker\u003A\u003AcheckProfile\u0028\u0029",
            "name": "checkProfile",
            "summary": "Check\u0020the\u0020PDF\u0020against\u0020a\u0020single\u0020conformance\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceChecker.html#method_checkProfile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceChecker\u003A\u003AcheckProfiles\u0028\u0029",
            "name": "checkProfiles",
            "summary": "Check\u0020the\u0020PDF\u0020against\u0020multiple\u0020conformance\u0020profiles.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceChecker.html#method_checkProfiles"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceChecker\u003A\u003AgetReader\u0028\u0029",
            "name": "getReader",
            "summary": "Get\u0020the\u0020underlying\u0020PdfReader\u0020for\u0020additional\u0020inspection.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceChecker.html#method_getReader"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceException",
            "name": "ConformanceException",
            "summary": "Thrown\u0020in\u0020strict\u0020mode\u0020when\u0020the\u0020document\u0020does\u0020not\u0020conform.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceException.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceException.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceException\u003A\u003A\u0024results",
            "name": "results",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceException.html#property_results"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceMode",
            "name": "ConformanceMode",
            "summary": "Value\u0020object\u0020holding\u0020the\u0020active\u0020conformance\u0020profile\u0028s\u0029\u0020and\u0020behavior\u0020mode.",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceMode.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceMode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceMode.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceMode\u003A\u003A\u0024profiles",
            "name": "profiles",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceMode.html#property_profiles"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\ConformanceMode\u003A\u003A\u0024strict",
            "name": "strict",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-ConformanceMode.html#property_strict"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ActionConstraint",
            "name": "ActionConstraint",
            "summary": "PDF\/A\u0020clause\u00206.5\u0020\/\u00206.6.1\u003A\u0020Restricted\u0020action\u0020types.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ActionConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ActionConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ActionConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\AnnotationConstraint",
            "name": "AnnotationConstraint",
            "summary": "PDF\/UA\u002D1\u0020clause\u00207.18.1\u003A\u0020Annotations\u0020must\u0020be\u0020accessible.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-AnnotationConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\AnnotationConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-AnnotationConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ColorSpaceConstraint",
            "name": "ColorSpaceConstraint",
            "summary": "PDF\/A\u0020clause\u00206.2\u003A\u0020Device\u002Ddependent\u0020color\u0020spaces\u0020are\u0020only\u0020allowed\nwhen\u0020a\u0020matching\u0020OutputIntent\u0020is\u0020present.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ColorSpaceConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ColorSpaceConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ColorSpaceConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ConformanceConstraint",
            "name": "ConformanceConstraint",
            "summary": "A\u0020single\u0020category\u0020of\u0020conformance\u0020checks\u0020\u0028e.g.\u0020font\u0020embedding,\u0020encryption\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ConformanceConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ConformanceConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ConformanceConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\DisplayDocTitleConstraint",
            "name": "DisplayDocTitleConstraint",
            "summary": "PDF\/UA\u002D1\u0020clause\u00207.18.1\u003A\u0020ViewerPreferences\u0020\/DisplayDocTitle\u0020must\u0020be\u0020true.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-DisplayDocTitleConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\DisplayDocTitleConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-DisplayDocTitleConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\DPartRootConstraint",
            "name": "DPartRootConstraint",
            "summary": "PDF\/VT\u003A\u0020Catalog\u0020must\u0020have\u0020a\u0020\/DPartRoot\u0020reference.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-DPartRootConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\DPartRootConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-DPartRootConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\EmbeddedFileConstraint",
            "name": "EmbeddedFileConstraint",
            "summary": "PDF\/A\u002D1\u0020clause\u00206.9\u0020\/\u0020PDF\/A\u002D2\u0020clause\u00206.10\u003A\u0020Embedded\u0020files\u0020are\u0020prohibited.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-EmbeddedFileConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\EmbeddedFileConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-EmbeddedFileConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\EncryptionConstraint",
            "name": "EncryptionConstraint",
            "summary": "PDF\/A\u0020clause\u00206.6\u003A\u0020Encryption\u0020is\u0020prohibited.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-EncryptionConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\EncryptionConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-EncryptionConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\FilterConstraint",
            "name": "FilterConstraint",
            "summary": "PDF\/A\u002D1\u0020clause\u00206.8\u003A\u0020LZWDecode\u0020filter\u0020is\u0020prohibited.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-FilterConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\FilterConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-FilterConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\FontEmbeddingConstraint",
            "name": "FontEmbeddingConstraint",
            "summary": "PDF\/A\u0020clause\u00206.3\u003A\u0020All\u0020fonts\u0020must\u0020be\u0020embedded.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-FontEmbeddingConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\FontEmbeddingConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-FontEmbeddingConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\FormConstraint",
            "name": "FormConstraint",
            "summary": "Prohibits\u0020interactive\u0020forms\u0020\u0028AcroForm\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-FormConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\FormConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-FormConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\MetadataConstraint",
            "name": "MetadataConstraint",
            "summary": "PDF\/A\u0020clause\u00206.7\u003A\u0020XMP\u0020metadata\u0020is\u0020required\u0020and\u0020must\u0020contain\u0020the\nconformance\u0020identification\u0020schema.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-MetadataConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\MetadataConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-MetadataConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\MultimediaConstraint",
            "name": "MultimediaConstraint",
            "summary": "Prohibits\u0020multimedia\u0020content\u0020\u0028movies,\u0020sounds,\u0020renditions,\u0020rich\u0020media\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-MultimediaConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\MultimediaConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-MultimediaConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\OutputIntentConstraint",
            "name": "OutputIntentConstraint",
            "summary": "PDF\/A\u0020clause\u00206.2.2\u003A\u0020At\u0020least\u0020one\u0020OutputIntent\u0020with\u0020the\u0020correct\nsubtype\u0020and\u0020an\u0020embedded\u0020ICC\u0020profile\u0020is\u0020required.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-OutputIntentConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\OutputIntentConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-OutputIntentConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfEActionConstraint",
            "name": "PdfEActionConstraint",
            "summary": "ISO\u002024517\u002D1\u0020\u0028PDF\/E\u002D1\u0029\u003A\u0020Action\u0020restrictions.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfEActionConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfEActionConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfEActionConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfEColorSpaceConstraint",
            "name": "PdfEColorSpaceConstraint",
            "summary": "ISO\u002024517\u002D1\u0020\u0028PDF\/E\u002D1\u0029\u003A\u0020Color\u0020space\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfEColorSpaceConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfEColorSpaceConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfEColorSpaceConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfRActionConstraint",
            "name": "PdfRActionConstraint",
            "summary": "ISO\u002023504\u002D1\u0020\u0028PDF\/R\u002D1\u0029\u003A\u0020Action\u0020restrictions.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfRActionConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfRActionConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfRActionConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfRFontConstraint",
            "name": "PdfRFontConstraint",
            "summary": "ISO\u002023504\u002D1\u0020\u0028PDF\/R\u002D1\u0029\u003A\u0020Font\u0020presence\u0020warning.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfRFontConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\PdfRFontConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-PdfRFontConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\RasterContentConstraint",
            "name": "RasterContentConstraint",
            "summary": "ISO\u002023504\u002D1\u0020\u0028PDF\/R\u002D1\u0029\u003A\u0020Raster\u0020content\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-RasterContentConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\RasterContentConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-RasterContentConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ReferenceXObjectConstraint",
            "name": "ReferenceXObjectConstraint",
            "summary": "ISO\u002015930\u002D8\/9\u0020\u0028PDF\/X\u002D5\u0029\u003A\u0020Reference\u0020XObject\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ReferenceXObjectConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ReferenceXObjectConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ReferenceXObjectConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TabOrderConstraint",
            "name": "TabOrderConstraint",
            "summary": "PDF\/UA\u002D1\u0020clause\u00207.5\u003A\u0020Every\u0020page\u0020that\u0020contains\u0020annotations\u0020must\nhave\u0020\/Tabs\u0020set\u0020to\u0020\/S\u0020\u0028structure\u0020order\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TabOrderConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TabOrderConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TabOrderConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TaggedStructureConstraint",
            "name": "TaggedStructureConstraint",
            "summary": "Tagged\u0020structure\u0020requirements\u0020for\u0020PDF\/A\u0020Level\u0020A\u0020and\u0020PDF\/UA.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TaggedStructureConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TaggedStructureConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TaggedStructureConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ThreeDContentConstraint",
            "name": "ThreeDContentConstraint",
            "summary": "ISO\u002024517\u002D1\u0020\u0028PDF\/E\u002D1\u0029\u003A\u00203D\u0020content\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ThreeDContentConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ThreeDContentConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ThreeDContentConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TransparencyConstraint",
            "name": "TransparencyConstraint",
            "summary": "Transparency\u0020prohibition\u0020for\u0020PDF\/A\u002D1\u0020\u0028clause\u00206.4\u0029\u0020and\u0020PDF\/X\u002D1a\/X\u002D3.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TransparencyConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TransparencyConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TransparencyConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TrappedConstraint",
            "name": "TrappedConstraint",
            "summary": "PDF\/X\u003A\u0020The\u0020Info\u0020dictionary\u0020\/Trapped\u0020key\u0020must\u0020be\u0020\/True\u0020or\u0020\/False.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TrappedConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TrappedConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TrappedConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TrimBoxConstraint",
            "name": "TrimBoxConstraint",
            "summary": "PDF\/X\u003A\u0020All\u0020pages\u0020must\u0020have\u0020\/TrimBox\u0020\u0028or\u0020\/ArtBox\u0020as\u0020fallback\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TrimBoxConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\TrimBoxConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-TrimBoxConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ZugferdInvoiceConstraint",
            "name": "ZugferdInvoiceConstraint",
            "summary": "ZUGFeRD\u0020\/\u0020Factur\u002DX\u003A\u0020Embedded\u0020invoice\u0020XML\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ZugferdInvoiceConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ZugferdInvoiceConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ZugferdInvoiceConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ZugferdXmpConstraint",
            "name": "ZugferdXmpConstraint",
            "summary": "ZUGFeRD\u0020\/\u0020Factur\u002DX\u003A\u0020XMP\u0020metadata\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ZugferdXmpConstraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint\\ZugferdXmpConstraint\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "Check\u0020the\u0020document\u0020against\u0020this\u0020constraint\u0020for\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Constraint-ZugferdXmpConstraint.html#method_check"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector",
            "name": "DocumentInspector",
            "summary": "Abstract\u0020inspection\u0020interface\u0020for\u0020conformance\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetCatalog\u0028\u0029",
            "name": "getCatalog",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getCatalog"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getInfo"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetPages\u0028\u0029",
            "name": "getPages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetFonts\u0028\u0029",
            "name": "getFonts",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getFonts"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasEncryption\u0028\u0029",
            "name": "hasEncryption",
            "summary": "Whether\u0020the\u0020document\u0020has\u0020encryption\u0020configured.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasEncryption"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasXmpMetadata\u0028\u0029",
            "name": "hasXmpMetadata",
            "summary": "Whether\u0020the\u0020catalog\u0020has\u0020an\u0020XMP\u0020metadata\u0020stream.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasXmpMetadata"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetXmpBytes\u0028\u0029",
            "name": "getXmpBytes",
            "summary": "Raw\u0020XMP\u0020XML\u0020bytes,\u0020or\u0020null\u0020if\u0020no\u0020metadata\u0020stream.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getXmpBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasOutputIntents\u0028\u0029",
            "name": "hasOutputIntents",
            "summary": "Whether\u0020the\u0020catalog\u0020has\u0020OutputIntents.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasOutputIntents"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasOutputIntentWithIccProfile\u0028\u0029",
            "name": "hasOutputIntentWithIccProfile",
            "summary": "Whether\u0020any\u0020OutputIntent\u0020has\u0020an\u0020embedded\u0020ICC\u0020profile\u0020\u0028\/DestOutputProfile\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasOutputIntentWithIccProfile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasTransparency\u0028\u0029",
            "name": "hasTransparency",
            "summary": "Whether\u0020any\u0020page\u0020uses\u0020a\u0020transparency\u0020group.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasTransparency"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasJavaScript\u0028\u0029",
            "name": "hasJavaScript",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020JavaScript\u0020actions.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasJavaScript"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasEmbeddedFiles\u0028\u0029",
            "name": "hasEmbeddedFiles",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020embedded\u0020files.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasEmbeddedFiles"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetRegisteredObjects\u0028\u0029",
            "name": "getRegisteredObjects",
            "summary": "All\u0020registered\u0020PdfObject\u0020instances.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getRegisteredObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasThreeDAnnotations\u0028\u0029",
            "name": "hasThreeDAnnotations",
            "summary": "Whether\u0020the\u0020document\u0020contains\u00203D\u0020annotations.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasThreeDAnnotations"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetThreeDStreams\u0028\u0029",
            "name": "getThreeDStreams",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getThreeDStreams"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasRasterOnlyContent\u0028\u0029",
            "name": "hasRasterOnlyContent",
            "summary": "Whether\u0020all\u0020page\u0020content\u0020is\u0020raster\u002Donly\u0020\u0028no\u0020text\u0020operators,\u0020no\u0020vector\u0020paths\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasRasterOnlyContent"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetImageXObjects\u0028\u0029",
            "name": "getImageXObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getImageXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasInteractiveForms\u0028\u0029",
            "name": "hasInteractiveForms",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020interactive\u0020forms\u0020\u0028AcroForm\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasInteractiveForms"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AhasMultimediaContent\u0028\u0029",
            "name": "hasMultimediaContent",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020multimedia\u0020content\u0020\u0028movies,\u0020sounds,\u0020renditions\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_hasMultimediaContent"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\DocumentInspector\u003A\u003AgetReferenceXObjects\u0028\u0029",
            "name": "getReferenceXObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-DocumentInspector.html#method_getReferenceXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector",
            "name": "ReaderDocumentInspector",
            "summary": "Inspects\u0020a\u0020parsed\u0020PDF\u0020\u0028via\u0020PdfReader\u0029\u0020for\u0020conformance\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetCatalog\u0028\u0029",
            "name": "getCatalog",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getCatalog"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getInfo"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetPages\u0028\u0029",
            "name": "getPages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetFonts\u0028\u0029",
            "name": "getFonts",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getFonts"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasEncryption\u0028\u0029",
            "name": "hasEncryption",
            "summary": "Whether\u0020the\u0020document\u0020has\u0020encryption\u0020configured.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasEncryption"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasXmpMetadata\u0028\u0029",
            "name": "hasXmpMetadata",
            "summary": "Whether\u0020the\u0020catalog\u0020has\u0020an\u0020XMP\u0020metadata\u0020stream.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasXmpMetadata"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetXmpBytes\u0028\u0029",
            "name": "getXmpBytes",
            "summary": "Raw\u0020XMP\u0020XML\u0020bytes,\u0020or\u0020null\u0020if\u0020no\u0020metadata\u0020stream.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getXmpBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasOutputIntents\u0028\u0029",
            "name": "hasOutputIntents",
            "summary": "Whether\u0020the\u0020catalog\u0020has\u0020OutputIntents.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasOutputIntents"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasOutputIntentWithIccProfile\u0028\u0029",
            "name": "hasOutputIntentWithIccProfile",
            "summary": "Whether\u0020any\u0020OutputIntent\u0020has\u0020an\u0020embedded\u0020ICC\u0020profile\u0020\u0028\/DestOutputProfile\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasOutputIntentWithIccProfile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasTransparency\u0028\u0029",
            "name": "hasTransparency",
            "summary": "Whether\u0020any\u0020page\u0020uses\u0020a\u0020transparency\u0020group.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasTransparency"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasJavaScript\u0028\u0029",
            "name": "hasJavaScript",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020JavaScript\u0020actions.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasJavaScript"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasEmbeddedFiles\u0028\u0029",
            "name": "hasEmbeddedFiles",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020embedded\u0020files.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasEmbeddedFiles"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetRegisteredObjects\u0028\u0029",
            "name": "getRegisteredObjects",
            "summary": "All\u0020registered\u0020PdfObject\u0020instances.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getRegisteredObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasThreeDAnnotations\u0028\u0029",
            "name": "hasThreeDAnnotations",
            "summary": "Whether\u0020the\u0020document\u0020contains\u00203D\u0020annotations.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasThreeDAnnotations"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetThreeDStreams\u0028\u0029",
            "name": "getThreeDStreams",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getThreeDStreams"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasRasterOnlyContent\u0028\u0029",
            "name": "hasRasterOnlyContent",
            "summary": "Whether\u0020all\u0020page\u0020content\u0020is\u0020raster\u002Donly\u0020\u0028no\u0020text\u0020operators,\u0020no\u0020vector\u0020paths\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasRasterOnlyContent"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetImageXObjects\u0028\u0029",
            "name": "getImageXObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getImageXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasInteractiveForms\u0028\u0029",
            "name": "hasInteractiveForms",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020interactive\u0020forms\u0020\u0028AcroForm\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasInteractiveForms"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AhasMultimediaContent\u0028\u0029",
            "name": "hasMultimediaContent",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020multimedia\u0020content\u0020\u0028movies,\u0020sounds,\u0020renditions\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_hasMultimediaContent"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\ReaderDocumentInspector\u003A\u003AgetReferenceXObjects\u0028\u0029",
            "name": "getReferenceXObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-ReaderDocumentInspector.html#method_getReferenceXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector",
            "name": "WriterDocumentInspector",
            "summary": "Inspects\u0020a\u0020PdfFileWriter\u0027s\u0020internal\u0020state\u0020for\u0020conformance\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetCatalog\u0028\u0029",
            "name": "getCatalog",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getCatalog"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetInfo\u0028\u0029",
            "name": "getInfo",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getInfo"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetPages\u0028\u0029",
            "name": "getPages",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getPages"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetFonts\u0028\u0029",
            "name": "getFonts",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getFonts"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasEncryption\u0028\u0029",
            "name": "hasEncryption",
            "summary": "Whether\u0020the\u0020document\u0020has\u0020encryption\u0020configured.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasEncryption"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasXmpMetadata\u0028\u0029",
            "name": "hasXmpMetadata",
            "summary": "Whether\u0020the\u0020catalog\u0020has\u0020an\u0020XMP\u0020metadata\u0020stream.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasXmpMetadata"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetXmpBytes\u0028\u0029",
            "name": "getXmpBytes",
            "summary": "Raw\u0020XMP\u0020XML\u0020bytes,\u0020or\u0020null\u0020if\u0020no\u0020metadata\u0020stream.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getXmpBytes"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasOutputIntents\u0028\u0029",
            "name": "hasOutputIntents",
            "summary": "Whether\u0020the\u0020catalog\u0020has\u0020OutputIntents.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasOutputIntents"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasOutputIntentWithIccProfile\u0028\u0029",
            "name": "hasOutputIntentWithIccProfile",
            "summary": "Whether\u0020any\u0020OutputIntent\u0020has\u0020an\u0020embedded\u0020ICC\u0020profile\u0020\u0028\/DestOutputProfile\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasOutputIntentWithIccProfile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasTransparency\u0028\u0029",
            "name": "hasTransparency",
            "summary": "Whether\u0020any\u0020page\u0020uses\u0020a\u0020transparency\u0020group.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasTransparency"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasJavaScript\u0028\u0029",
            "name": "hasJavaScript",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020JavaScript\u0020actions.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasJavaScript"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasEmbeddedFiles\u0028\u0029",
            "name": "hasEmbeddedFiles",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020embedded\u0020files.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasEmbeddedFiles"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetRegisteredObjects\u0028\u0029",
            "name": "getRegisteredObjects",
            "summary": "All\u0020registered\u0020PdfObject\u0020instances.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getRegisteredObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasThreeDAnnotations\u0028\u0029",
            "name": "hasThreeDAnnotations",
            "summary": "Whether\u0020the\u0020document\u0020contains\u00203D\u0020annotations.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasThreeDAnnotations"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetThreeDStreams\u0028\u0029",
            "name": "getThreeDStreams",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getThreeDStreams"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasRasterOnlyContent\u0028\u0029",
            "name": "hasRasterOnlyContent",
            "summary": "Whether\u0020all\u0020page\u0020content\u0020is\u0020raster\u002Donly\u0020\u0028no\u0020text\u0020operators,\u0020no\u0020vector\u0020paths\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasRasterOnlyContent"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetImageXObjects\u0028\u0029",
            "name": "getImageXObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getImageXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasInteractiveForms\u0028\u0029",
            "name": "hasInteractiveForms",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020interactive\u0020forms\u0020\u0028AcroForm\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasInteractiveForms"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AhasMultimediaContent\u0028\u0029",
            "name": "hasMultimediaContent",
            "summary": "Whether\u0020the\u0020document\u0020contains\u0020multimedia\u0020content\u0020\u0028movies,\u0020sounds,\u0020renditions\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_hasMultimediaContent"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection\\WriterDocumentInspector\u003A\u003AgetReferenceXObjects\u0028\u0029",
            "name": "getReferenceXObjects",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Inspection-WriterDocumentInspector.html#method_getReferenceXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Metadata\\ConformanceXmpWriter",
            "name": "ConformanceXmpWriter",
            "summary": "Builds\u0020XMP\u0020metadata\u0020with\u0020the\u0020conformance\u0020identification\u0020schema.",
            "url": "classes/Phpdftk-Pdf-Conformance-Metadata-ConformanceXmpWriter.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Metadata\\ConformanceXmpWriter\u003A\u003AbuildXmp\u0028\u0029",
            "name": "buildXmp",
            "summary": "Build\u0020a\u0020complete\u0020XMP\u0020packet\u0020with\u0020conformance\u0020identification.",
            "url": "classes/Phpdftk-Pdf-Conformance-Metadata-ConformanceXmpWriter.html#method_buildXmp"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile",
            "name": "ConformanceProfile",
            "summary": "Represents\u0020a\u0020PDF\u0020subset\u0020conformance\u0020profile\u0020\u0028e.g.\u0020PDF\/A\u002D1b,\u0020PDF\/X\u002D4,\u0020PDF\/UA\u002D1\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "Standard\u0020family\u0020name\u0020\u0028e.g.\u0020\u0027PDF\/A\u0027,\u0020\u0027PDF\/X\u0027,\u0020\u0027PDF\/UA\u0027\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "Conformance\u0020level\u0020label\u0020\u0028e.g.\u0020\u00271b\u0027,\u0020\u0027X\u002D4\u0027,\u0020\u0027UA\u002D1\u0027\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "Minimum\u0020PDF\u0020version\u0020required\u0020by\u0020this\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "XMP\u0020namespace\u0020URI\u0020for\u0020the\u0020identification\u0020schema.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "XMP\u0020namespace\u0020prefix\u0020\u0028e.g.\u0020\u0027pdfaid\u0027,\u0020\u0027pdfxid\u0027\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ConformanceProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "XMP\u0020identification\u0020properties\u0020for\u0020this\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ConformanceProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile",
            "name": "PdfAProfile",
            "summary": "PDF\/A\u0020conformance\u0020profiles\u0020\u0028ISO\u002019005\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetPart\u0028\u0029",
            "name": "getPart",
            "summary": "ISO\u002019005\u0020part\u0020number\u0020\u00281,\u00202,\u00203,\u0020or\u00204\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getPart"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetConformanceLevel\u0028\u0029",
            "name": "getConformanceLevel",
            "summary": "Conformance\u0020level\u0020letter\u0020\u0028a,\u0020b,\u0020u,\u0020e,\u0020f\u0029\u0020or\u0020null\u0020for\u0020PDF\/A\u002D4\u0020base.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getConformanceLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003ArequiresTaggedStructure\u0028\u0029",
            "name": "requiresTaggedStructure",
            "summary": "Whether\u0020this\u0020profile\u0020requires\u0020Level\u0020A\u0020\u0028tagged\u0020PDF\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_requiresTaggedStructure"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AprohibitsTransparency\u0028\u0029",
            "name": "prohibitsTransparency",
            "summary": "Whether\u0020this\u0020profile\u0020prohibits\u0020transparency\u0020\u0028PDF\/A\u002D1\u0020only\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_prohibitsTransparency"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AallowsEmbeddedFiles\u0028\u0029",
            "name": "allowsEmbeddedFiles",
            "summary": "Whether\u0020this\u0020profile\u0020allows\u0020embedded\u0020files\u0020\u0028PDF\/A\u002D3\u002B\u0020only\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#method_allowsEmbeddedFiles"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA1a",
            "name": "A1a",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A1a"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA1b",
            "name": "A1b",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A1b"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA2a",
            "name": "A2a",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A2a"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA2b",
            "name": "A2b",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A2b"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA2u",
            "name": "A2u",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A2u"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA3a",
            "name": "A3a",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A3a"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA3b",
            "name": "A3b",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A3b"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA3u",
            "name": "A3u",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A3u"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA4",
            "name": "A4",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A4"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA4e",
            "name": "A4e",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A4e"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfAProfile\u003A\u003AA4f",
            "name": "A4f",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfAProfile.html#enumcase_A4f"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile",
            "name": "PdfEProfile",
            "summary": "PDF\/E\u0020conformance\u0020profiles\u0020\u0028ISO\u002024517\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfEProfile\u003A\u003AE1",
            "name": "E1",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfEProfile.html#enumcase_E1"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile",
            "name": "PdfMailProfile",
            "summary": "PDF\/mail\u0020conformance\u0020profile\u0020\u0028ISO\u002023053\u002D2\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfMailProfile\u003A\u003AMail1",
            "name": "Mail1",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfMailProfile.html#enumcase_Mail1"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile",
            "name": "PdfRProfile",
            "summary": "PDF\/R\u0020conformance\u0020profiles\u0020\u0028ISO\u002023504\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfRProfile\u003A\u003AR1",
            "name": "R1",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfRProfile.html#enumcase_R1"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile",
            "name": "PdfUaProfile",
            "summary": "PDF\/UA\u0020conformance\u0020profiles\u0020\u0028ISO\u002014289\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetPart\u0028\u0029",
            "name": "getPart",
            "summary": "ISO\u002014289\u0020part\u0020number\u0020\u00281\u0020or\u00202\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getPart"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AUA1",
            "name": "UA1",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#enumcase_UA1"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfUaProfile\u003A\u003AUA2",
            "name": "UA2",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfUaProfile.html#enumcase_UA2"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile",
            "name": "PdfVtProfile",
            "summary": "PDF\/VT\u0020conformance\u0020profiles\u0020\u0028ISO\u002016612\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AVT1",
            "name": "VT1",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#enumcase_VT1"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AVT2",
            "name": "VT2",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#enumcase_VT2"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfVtProfile\u003A\u003AVT2s",
            "name": "VT2s",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfVtProfile.html#enumcase_VT2s"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile",
            "name": "PdfXProfile",
            "summary": "PDF\/X\u0020conformance\u0020profiles\u0020\u0028ISO\u002015930\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AprohibitsTransparency\u0028\u0029",
            "name": "prohibitsTransparency",
            "summary": "Whether\u0020this\u0020profile\u0020prohibits\u0020transparency.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_prohibitsTransparency"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AgetOutputIntentSubtype\u0028\u0029",
            "name": "getOutputIntentSubtype",
            "summary": "The\u0020required\u0020OutputIntent\u0020\/S\u0020subtype\u0020value.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_getOutputIntentSubtype"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AsupportsReferenceXObjects\u0028\u0029",
            "name": "supportsReferenceXObjects",
            "summary": "Whether\u0020this\u0020profile\u0020supports\u0020reference\u0020XObjects\u0020for\u0020external\u0020content.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#method_supportsReferenceXObjects"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AX1a2003",
            "name": "X1a2003",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#enumcase_X1a2003"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AX32003",
            "name": "X32003",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#enumcase_X32003"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AX4",
            "name": "X4",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#enumcase_X4"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AX5g",
            "name": "X5g",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#enumcase_X5g"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AX5pg",
            "name": "X5pg",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#enumcase_X5pg"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\PdfXProfile\u003A\u003AX5n",
            "name": "X5n",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-PdfXProfile.html#enumcase_X5n"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile",
            "name": "ZugferdProfile",
            "summary": "ZUGFeRD\u0020\/\u0020Factur\u002DX\u0020conformance\u0020profiles.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetFamily\u0028\u0029",
            "name": "getFamily",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getFamily"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetLevel\u0028\u0029",
            "name": "getLevel",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getLevel"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetPdfVersion\u0028\u0029",
            "name": "getPdfVersion",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getPdfVersion"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetXmpNamespace\u0028\u0029",
            "name": "getXmpNamespace",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getXmpNamespace"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetXmpPrefix\u0028\u0029",
            "name": "getXmpPrefix",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getXmpPrefix"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetXmpProperties\u0028\u0029",
            "name": "getXmpProperties",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getXmpProperties"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AgetBaseProfile\u0028\u0029",
            "name": "getBaseProfile",
            "summary": "The\u0020base\u0020PDF\/A\u0020profile\u0020required\u0020for\u0020ZUGFeRD.",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#method_getBaseProfile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AMINIMUM",
            "name": "MINIMUM",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#enumcase_MINIMUM"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003ABASIC_WL",
            "name": "BASIC_WL",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#enumcase_BASIC_WL"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003ABASIC",
            "name": "BASIC",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#enumcase_BASIC"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AEN16931",
            "name": "EN16931",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#enumcase_EN16931"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AEXTENDED",
            "name": "EXTENDED",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#enumcase_EXTENDED"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile\\ZugferdProfile\u003A\u003AXRECHNUNG",
            "name": "XRECHNUNG",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Profile-ZugferdProfile.html#enumcase_XRECHNUNG"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult",
            "name": "ConformanceResult",
            "summary": "The\u0020result\u0020of\u0020validating\u0020a\u0020document\u0020against\u0020a\u0020conformance\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult\u003A\u003AgetErrors\u0028\u0029",
            "name": "getErrors",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html#method_getErrors"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult\u003A\u003AgetWarnings\u0028\u0029",
            "name": "getWarnings",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html#method_getWarnings"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult\u003A\u003A\u0024profile",
            "name": "profile",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html#property_profile"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult\u003A\u003A\u0024isCompliant",
            "name": "isCompliant",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html#property_isCompliant"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceResult\u003A\u003A\u0024violations",
            "name": "violations",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceResult.html#property_violations"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceViolation",
            "name": "ConformanceViolation",
            "summary": "A\u0020single\u0020conformance\u0020violation\u0020detected\u0020during\u0020validation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceViolation.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceViolation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceViolation.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceViolation\u003A\u003A\u0024clause",
            "name": "clause",
            "summary": "ISO\u0020clause\u0020reference\u0020\u0028e.g.\u0020\u00226.3.4\u0022\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceViolation.html#property_clause"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceViolation\u003A\u003A\u0024message",
            "name": "message",
            "summary": "Human\u002Dreadable\u0020description\u0020of\u0020the\u0020violation.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceViolation.html#property_message"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceViolation\u003A\u003A\u0024severity",
            "name": "severity",
            "summary": "Severity\u0020level.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceViolation.html#property_severity"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ConformanceViolation\u003A\u003A\u0024objectPath",
            "name": "objectPath",
            "summary": "Path\u0020to\u0020the\u0020offending\u0020object\u0020\u0028e.g.\u0020\u0022Page\u005B0\u005D.Resources.Font\u005BF1\u005D\u0022\u0029.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ConformanceViolation.html#property_objectPath"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ViolationSeverity",
            "name": "ViolationSeverity",
            "summary": "Severity\u0020levels\u0020for\u0020conformance\u0020violations.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ViolationSeverity.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ViolationSeverity\u003A\u003AError",
            "name": "Error",
            "summary": "Hard\u0020failure\u0020\u2014\u0020the\u0020document\u0020does\u0020not\u0020conform.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ViolationSeverity.html#enumcase_Error"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result\\ViolationSeverity\u003A\u003AWarning",
            "name": "Warning",
            "summary": "Advisory\u0020\u2014\u0020potential\u0020conformance\u0020issue\u0020that\u0020may\u0020pass\u0020some\u0020validators.",
            "url": "classes/Phpdftk-Pdf-Conformance-Result-ViolationSeverity.html#enumcase_Warning"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator\\ConformanceValidator",
            "name": "ConformanceValidator",
            "summary": "Orchestrates\u0020conformance\u0020validation\u003A\u0020runs\u0020all\u0020applicable\u0020constraints\nfor\u0020a\u0020profile\u0020against\u0020a\u0020document\u0020inspector\u0020and\u0020returns\u0020a\u0020result.",
            "url": "classes/Phpdftk-Pdf-Conformance-Validator-ConformanceValidator.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator\\ConformanceValidator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Pdf-Conformance-Validator-ConformanceValidator.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator\\ConformanceValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020a\u0020document\u0020against\u0020a\u0020single\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Validator-ConformanceValidator.html#method_validate"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator\\ConformanceValidator\u003A\u003AvalidateAll\u0028\u0029",
            "name": "validateAll",
            "summary": "Validate\u0020a\u0020document\u0020against\u0020multiple\u0020profiles.",
            "url": "classes/Phpdftk-Pdf-Conformance-Validator-ConformanceValidator.html#method_validateAll"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator\\ProfileConstraintRegistry",
            "name": "ProfileConstraintRegistry",
            "summary": "Maps\u0020each\u0020conformance\u0020profile\u0020to\u0020its\u0020set\u0020of\u0020applicable\u0020constraints.",
            "url": "classes/Phpdftk-Pdf-Conformance-Validator-ProfileConstraintRegistry.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator\\ProfileConstraintRegistry\u003A\u003AgetConstraints\u0028\u0029",
            "name": "getConstraints",
            "summary": "Get\u0020the\u0020constraints\u0020applicable\u0020to\u0020the\u0020given\u0020profile.",
            "url": "classes/Phpdftk-Pdf-Conformance-Validator-ProfileConstraintRegistry.html#method_getConstraints"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance",
            "name": "Conformance",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf",
            "name": "Pdf",
            "summary": "",
            "url": "namespaces/phpdftk-pdf.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Constraint",
            "name": "Constraint",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance-constraint.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Inspection",
            "name": "Inspection",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance-inspection.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Metadata",
            "name": "Metadata",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance-metadata.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Profile",
            "name": "Profile",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance-profile.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Result",
            "name": "Result",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance-result.html"
        },                {
            "fqsen": "\\Phpdftk\\Pdf\\Conformance\\Validator",
            "name": "Validator",
            "summary": "",
            "url": "namespaces/phpdftk-pdf-conformance-validator.html"
        }            ]
);
