<?php

declare(strict_types=1);

require_once __DIR__ . '/../../bootstrap.php';

chdir(__DIR__);

// region: example
use Phpdftk\Pdf\Core\Action\JavaScriptAction;
use Phpdftk\Pdf\Core\Annotation\WidgetAnnotation;
use Phpdftk\Pdf\Core\Font\StandardFont;
use Phpdftk\Pdf\Core\Font\Type1Font;
use Phpdftk\Pdf\Core\Interactive\Form\AcroForm;
use Phpdftk\Pdf\Core\Interactive\Form\ButtonField;
use Phpdftk\Pdf\Core\Interactive\Form\TextField;
use Phpdftk\Pdf\Core\PdfArray;
use Phpdftk\Pdf\Core\PdfNumber;
use Phpdftk\Pdf\Core\PdfReference;
use Phpdftk\Pdf\Core\PdfString;
use Phpdftk\Pdf\Writer\PdfWriter;

$writer = new PdfWriter();
$page = $writer->addPage();
$body = $writer->addFont(new Type1Font(StandardFont::Helvetica));
$bold = $writer->addFont(new Type1Font(StandardFont::HelveticaBold));

$cs = $writer->addContentStream($page);
$cs->beginText()->setFont($bold, 22)->moveTextPosition(72, 740)
    ->showText('JavaScript Actions')->endText();
$cs->beginText()->setFont($body, 11)->moveTextPosition(72, 706)
    ->showText('When opened, this PDF runs a script that greets the reader.')
    ->endText();
$cs->beginText()->setFont($body, 11)->moveTextPosition(72, 690)
    ->showText('Click the button below to run another script on demand.')
    ->endText();

// Page text labelling the interactive regions.
$cs->beginText()->setFont($bold, 12)->moveTextPosition(96, 632)
    ->showText('Roll the dice')->endText();
$cs->beginText()->setFont($body, 10)->moveTextPosition(246, 632)
    ->showText('Result appears here ->')->endText();

// 1) /OpenAction — a script that fires when the document is opened.
$openJs = new JavaScriptAction(new PdfString(
    'app.alert({cMsg: "Welcome — generated by phpdftk.", cTitle: "phpdftk"});',
));
$writer->getCatalog()->openAction = $writer->register($openJs);

// 2) A pushbutton that runs JavaScript on click.
$clickJs = new JavaScriptAction(new PdfString(
    'var n = Math.floor(Math.random() * 100); ' .
    'this.getField("result").value = "Random number: " + n;',
));
$clickJsRef = $writer->register($clickJs);

$button = new ButtonField();
$button->t  = new PdfString('roll');
$button->tu = new PdfString('Roll the dice');
$button->ff = 1 << 16; // pushbutton flag
$buttonRef = $writer->register($button);

$buttonWidget = new WidgetAnnotation(new PdfArray([
    new PdfNumber(72),  new PdfNumber(620),
    new PdfNumber(220), new PdfNumber(650),
]));
$buttonWidget->parent = $buttonRef;
$buttonWidget->a = $clickJsRef;
$page->corePage()->annots[] = $writer->register($buttonWidget);

// 3) A text field where the button script writes its result.
$result = new TextField();
$result->t  = new PdfString('result');
$result->tu = new PdfString('Result');
$result->v  = new PdfString('(click the button)');
$resultRef = $writer->register($result);

$resultWidget = new WidgetAnnotation(new PdfArray([
    new PdfNumber(240), new PdfNumber(620),
    new PdfNumber(500), new PdfNumber(650),
]));
$resultWidget->parent = $resultRef;
$page->corePage()->annots[] = $writer->register($resultWidget);

$form = new AcroForm();
$form->fields = [$buttonRef, $resultRef];
$form->needAppearances = true;
$form->da = new PdfString('/F1 12 Tf 0 g');
$writer->getCatalog()->acroForm = $writer->register($form);

$writer->save('javascript-actions.pdf');
// endregion

rename(__DIR__ . '/javascript-actions.pdf', example_output_path('core/interactive/javascript-actions.pdf'));
