Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Encoding\\CMapParser",
            "name": "CMapParser",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-CMapParser.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\CMapParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse\u0020a\u0020PDF\u0020CMap\u0020stream\u0020and\u0020return\u0020character\u0020code\u0020to\u0020Unicode\u0020codepoint\u0020mapping.",
            "url": "classes/Phpdftk-Encoding-CMapParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\GlyphList",
            "name": "GlyphList",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-GlyphList.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\GlyphList\u003A\u003AgetList\u0028\u0029",
            "name": "getList",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-GlyphList.html#method_getList"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\GlyphList\u003A\u003AglyphToUnicode\u0028\u0029",
            "name": "glyphToUnicode",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-GlyphList.html#method_glyphToUnicode"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\GlyphList\u003A\u003AunicodeToGlyph\u0028\u0029",
            "name": "unicodeToGlyph",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-GlyphList.html#method_unicodeToGlyph"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\MacExpertEncodingTable",
            "name": "MacExpertEncodingTable",
            "summary": "MacExpertEncoding\u0020\u2014\u0020used\u0020by\u0020expert\/small\u002Dcaps\u0020Type\u00201\u0020fonts\u0020on\u0020Mac.",
            "url": "classes/Phpdftk-Encoding-MacExpertEncodingTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\MacExpertEncodingTable\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-MacExpertEncodingTable.html#method_getTable"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\MacRomanTable",
            "name": "MacRomanTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-MacRomanTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\MacRomanTable\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-MacRomanTable.html#method_getTable"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PdfDocEncodingTable",
            "name": "PdfDocEncodingTable",
            "summary": "PDFDocEncoding\u0020\u2014\u0020the\u0020encoding\u0020for\u0020PDF\u0020text\u0020strings\u0020\u0028Info\u0020dict,\u0020bookmarks,\u0020annotations\u0029\nwhen\u0020they\u0020don\u0027t\u0020start\u0020with\u0020the\u0020UTF\u002D16BE\u0020BOM\u0020\u0028U\u002BFEFF\u0020\/\u00200xFE\u00200xFF\u0029.",
            "url": "classes/Phpdftk-Encoding-PdfDocEncodingTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PdfDocEncodingTable\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PdfDocEncodingTable.html#method_getTable"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PdfDocEncodingTable\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decode\u0020a\u0020PDFDocEncoding\u0020byte\u0020string\u0020to\u0020a\u0020UTF\u002D8\u0020string.",
            "url": "classes/Phpdftk-Encoding-PdfDocEncodingTable.html#method_decode"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PdfDocEncodingTable\u003A\u003AdecodeTextString\u0028\u0029",
            "name": "decodeTextString",
            "summary": "Decode\u0020a\u0020PDF\u0020text\u0020string\u0020\u2014\u0020auto\u002Ddetects\u0020UTF\u002D16BE\u0020\u0028BOM\u0029\u0020vs\u0020PDFDocEncoding.",
            "url": "classes/Phpdftk-Encoding-PdfDocEncodingTable.html#method_decodeTextString"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap",
            "name": "PredefinedCMap",
            "summary": "Predefined\u0020CMap\u0020names\u0020for\u0020CJK\u0020font\u0020encoding\u0020\u2014\u0020ISO\u002032000\u002D2\u0020\u00A79.7.5.",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AgetCIDSystemInfo\u0028\u0029",
            "name": "getCIDSystemInfo",
            "summary": "Get\u0020the\u0020CIDSystemInfo\u0020registry\/ordering\/supplement\u0020for\u0020a\u0020CMap\u0020name.",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#method_getCIDSystemInfo"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AisPredefined\u0028\u0029",
            "name": "isPredefined",
            "summary": "Check\u0020if\u0020a\u0020CMap\u0020name\u0020is\u0020a\u0020predefined\u0020CMap\u0020\u0028built\u0020into\u0020PDF\u0020viewers\u0029.",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#method_isPredefined"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_EUC",
            "name": "JAPAN_EUC",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_EUC"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_SJIS_H",
            "name": "JAPAN_SJIS_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_SJIS_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_SJIS_V",
            "name": "JAPAN_SJIS_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_SJIS_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_UCS2_H",
            "name": "JAPAN_UCS2_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_UCS2_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_UCS2_V",
            "name": "JAPAN_UCS2_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_UCS2_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_UTF16_H",
            "name": "JAPAN_UTF16_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_UTF16_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AJAPAN_UTF16_V",
            "name": "JAPAN_UTF16_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_JAPAN_UTF16_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AKOREA_UHC_H",
            "name": "KOREA_UHC_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_KOREA_UHC_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AKOREA_UHC_V",
            "name": "KOREA_UHC_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_KOREA_UHC_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AKOREA_UCS2_H",
            "name": "KOREA_UCS2_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_KOREA_UCS2_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AKOREA_UCS2_V",
            "name": "KOREA_UCS2_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_KOREA_UCS2_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AKOREA_UTF16_H",
            "name": "KOREA_UTF16_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_KOREA_UTF16_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AKOREA_UTF16_V",
            "name": "KOREA_UTF16_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_KOREA_UTF16_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AGB_GBK_H",
            "name": "GB_GBK_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_GB_GBK_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AGB_GBK_V",
            "name": "GB_GBK_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_GB_GBK_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AGB_UCS2_H",
            "name": "GB_UCS2_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_GB_UCS2_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AGB_UCS2_V",
            "name": "GB_UCS2_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_GB_UCS2_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AGB_UTF16_H",
            "name": "GB_UTF16_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_GB_UTF16_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AGB_UTF16_V",
            "name": "GB_UTF16_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_GB_UTF16_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003ACNS_BIG5_H",
            "name": "CNS_BIG5_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_CNS_BIG5_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003ACNS_BIG5_V",
            "name": "CNS_BIG5_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_CNS_BIG5_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003ACNS_UCS2_H",
            "name": "CNS_UCS2_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_CNS_UCS2_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003ACNS_UCS2_V",
            "name": "CNS_UCS2_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_CNS_UCS2_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003ACNS_UTF16_H",
            "name": "CNS_UTF16_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_CNS_UTF16_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003ACNS_UTF16_V",
            "name": "CNS_UTF16_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_CNS_UTF16_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AIDENTITY_H",
            "name": "IDENTITY_H",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_IDENTITY_H"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\PredefinedCMap\u003A\u003AIDENTITY_V",
            "name": "IDENTITY_V",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-PredefinedCMap.html#constant_IDENTITY_V"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\StandardEncodingTable",
            "name": "StandardEncodingTable",
            "summary": "StandardEncoding\u0020\u2014\u0020the\u0020default\u0020encoding\u0020for\u0020Type\u00201\u0020fonts\u0020when\u0020no\u0020\/Encoding\u0020is\u0020specified.",
            "url": "classes/Phpdftk-Encoding-StandardEncodingTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\StandardEncodingTable\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-StandardEncodingTable.html#method_getTable"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\TextEncoder",
            "name": "TextEncoder",
            "summary": "Converts\u0020a\u0020UTF\u002D8\u0020string\u0020into\u0020the\u0020byte\u0020sequence\u0020expected\u0020by\u0020a\u0020PDF\u0020font\u0027s\nencoding\u0020\u0028e.g.\u0020WinAnsi\u0029.",
            "url": "classes/Phpdftk-Encoding-TextEncoder.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\TextEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Encode\u0020UTF\u002D8\u0020input\u0020to\u0020the\u0020target\u0020encoding.\u0020Unmappable\u0020codepoints\u0020are\nsubstituted\u0020with\u00200x3F\u0020\u0028\u0027\u003F\u0027\u0029\u0020and\u0020recorded\u0020for\u0020later\u0020inspection.",
            "url": "classes/Phpdftk-Encoding-TextEncoder.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\TextEncoder\u003A\u003AgetMissingCodepoints\u0028\u0029",
            "name": "getMissingCodepoints",
            "summary": "Codepoints\u0020encountered\u0020since\u0020construction\u0020that\u0020could\u0020not\u0020be\u0020mapped.",
            "url": "classes/Phpdftk-Encoding-TextEncoder.html#method_getMissingCodepoints"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\WinAnsiEncoder",
            "name": "WinAnsiEncoder",
            "summary": "Encodes\u0020UTF\u002D8\u0020strings\u0020to\u0020WinAnsi\u0020\u0028single\u002Dbyte,\u0020ISO\u00208859\u002D1\u0020\u002B\u0020Microsoft\nadditions\u0020in\u00200x80\u20130x9F\u0029\u0020for\u0020use\u0020with\u0020Type1\u0020standard\u0020fonts\u0020and\u0020any\u0020other\nfont\u0020whose\u0020\/Encoding\u0020is\u0020WinAnsiEncoding.",
            "url": "classes/Phpdftk-Encoding-WinAnsiEncoder.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\WinAnsiEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Encode\u0020UTF\u002D8\u0020input\u0020to\u0020the\u0020target\u0020encoding.\u0020Unmappable\u0020codepoints\u0020are\nsubstituted\u0020with\u00200x3F\u0020\u0028\u0027\u003F\u0027\u0029\u0020and\u0020recorded\u0020for\u0020later\u0020inspection.",
            "url": "classes/Phpdftk-Encoding-WinAnsiEncoder.html#method_encode"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\WinAnsiEncoder\u003A\u003AgetMissingCodepoints\u0028\u0029",
            "name": "getMissingCodepoints",
            "summary": "Codepoints\u0020encountered\u0020since\u0020construction\u0020that\u0020could\u0020not\u0020be\u0020mapped.",
            "url": "classes/Phpdftk-Encoding-WinAnsiEncoder.html#method_getMissingCodepoints"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\WinAnsiTable",
            "name": "WinAnsiTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-WinAnsiTable.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding\\WinAnsiTable\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/Phpdftk-Encoding-WinAnsiTable.html#method_getTable"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Encoding",
            "name": "Encoding",
            "summary": "",
            "url": "namespaces/phpdftk-encoding.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
