<?php

declare(strict_types=1);

namespace ApprLabs\Pdf\Writer\Tests;

use ApprLabs\Pdf\Writer\Alignment;
use ApprLabs\Pdf\Writer\PageSize;
use ApprLabs\Pdf\Writer\Pdf;
use ApprLabs\Pdf\Writer\TextStyle;
use ApprLabs\Pdf\Writer\Theme;
use ApprLabs\Tests\Support\QpdfValidationTrait;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\TestCase;

/**
 * End-to-end integration test for the high-level {@see Pdf} builder.
 *
 * Generates a real multi-page PDF exercising headings, body text,
 * spacers, rules, alignment overrides, automatic pagination, and all
 * three output modes (save / toBytes / writeTo).
 */
#[Group("qpdf")]
class PdfIntegrationTest extends TestCase
{
    use QpdfValidationTrait;

    private const OUTPUT_FILE = __DIR__ . '/../../../../../docs/sample-pdfs/high_level_pdf.pdf';

    public function testGeneratesHighLevelDocument(): void
    {
        $pdf = new Pdf(PageSize::Letter, (new Theme())->withFont('Helvetica', 11), compressStreams: false);

        $pdf->addHeading('phpdftk High-Level Builder', 1);
        $pdf->addText('This sample document was generated by the new Pdf class, '
            . 'the friendly facade on top of PdfWriter. It requires no knowledge '
            . 'of content streams, resource names, font references, or any other '
            . 'PDF object-model machinery.');

        $pdf->addHeading('Text flows naturally', 2);
        $pdf->addText('Body paragraphs wrap at the content column and flow down '
            . 'the page. When the cursor runs out of room, a new page starts '
            . 'automatically and the next line of text continues there.');

        $pdf->addRule();

        $pdf->addHeading('Alignment', 3);
        $pdf->addText('Left-aligned is the default.', new TextStyle(alignment: Alignment::Left));
        $pdf->addText('This line is centered.',      new TextStyle(alignment: Alignment::Center));
        $pdf->addText('This line is right-aligned.', new TextStyle(alignment: Alignment::Right));

        $pdf->addSpacer(20);
        $pdf->addHeading('Output modes', 3);
        $pdf->addText('save(string $path) writes to a file on disk.');
        $pdf->addText('toBytes() returns the PDF as a string.');
        $pdf->addText('writeTo($stream) pipes the PDF to any fwrite-compatible resource.');

        // Force a second page and add filler to exercise auto-pagination.
        $pdf->newPage();
        $pdf->addHeading('Page 2: auto-pagination stress', 1);
        for ($i = 1; $i <= 60; $i++) {
            $pdf->addText("Filler paragraph number $i. Lorem ipsum dolor sit amet, "
                . 'consectetur adipiscing elit, sed do eiusmod tempor incididunt ut '
                . 'labore et dolore magna aliqua.');
        }

        // --- Three output modes ---------------------------------------
        $pdf->save(self::OUTPUT_FILE);
        self::assertFileExists(self::OUTPUT_FILE);
        $fileContent = (string) file_get_contents(self::OUTPUT_FILE);

        $bytes = $pdf->toBytes();
        self::assertStringStartsWith('%PDF-', $bytes);
        self::assertStringEndsWith('%%EOF', $bytes);

        $stream = fopen('php://memory', 'w+');
        self::assertIsResource($stream);
        $pdf->writeTo($stream);
        rewind($stream);
        $streamContent = (string) stream_get_contents($stream);
        fclose($stream);
        self::assertStringStartsWith('%PDF-', $streamContent);

        // --- Structural assertions ------------------------------------
        self::assertStringContainsString('/Type /Catalog', $fileContent);
        self::assertStringContainsString('/Type /Pages',   $fileContent);
        self::assertStringContainsString('/Type /Page',    $fileContent);
        self::assertStringContainsString('/Helvetica',     $fileContent);
        self::assertStringContainsString('(phpdftk High-Level Builder)', $fileContent);
        self::assertStringContainsString('(Filler paragraph number 1.', $fileContent);
        // Auto-pagination + explicit newPage should produce 3+ pages.
        self::assertMatchesRegularExpression('#/Count [3-9]#', $fileContent);

        // QPDF structural validation
        $this->assertQpdfValid(self::OUTPUT_FILE);
        $this->assertQpdfValidBytes($bytes);
    }
}
