Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\GifParser",
            "name": "GifParser",
            "summary": "Parse\u0020GIF\u0020logical\u0020screen\u0020descriptor\u0020for\u0020dimensions\u0020and\u0020color\u0020info.",
            "url": "classes/Phpdftk-ImageMetadata-GifParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\GifParser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-GifParser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\GifParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-GifParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo",
            "name": "ImageInfo",
            "summary": "Parsed\u0020image\u0020header\u0020metadata\u0020\u2014\u0020everything\u0020needed\u0020to\u0020build\u0020a\u0020PDF\u0020ImageXObject\nwithout\u0020decoding\u0020pixel\u0020data.",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_width"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_height"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024colorSpace",
            "name": "colorSpace",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_colorSpace"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024bitsPerComponent",
            "name": "bitsPerComponent",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_bitsPerComponent"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024format",
            "name": "format",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_format"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024hasAlpha",
            "name": "hasAlpha",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_hasAlpha"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024xDpi",
            "name": "xDpi",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_xDpi"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024yDpi",
            "name": "yDpi",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_yDpi"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024iccProfile",
            "name": "iccProfile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_iccProfile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageInfo\u003A\u003A\u0024intrinsicRatio",
            "name": "intrinsicRatio",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageInfo.html#property_intrinsicRatio"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageParser",
            "name": "ImageParser",
            "summary": "Detect\u0020image\u0020format\u0020from\u0020magic\u0020bytes\u0020and\u0020delegate\u0020to\u0020the\u0020format\u002Dspecific\u0020parser.",
            "url": "classes/Phpdftk-ImageMetadata-ImageParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\ImageParser\u003A\u003AparseString\u0028\u0029",
            "name": "parseString",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-ImageParser.html#method_parseString"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\Jbig2Parser",
            "name": "Jbig2Parser",
            "summary": "Parse\u0020JBIG2\u0020image\u0020headers.",
            "url": "classes/Phpdftk-ImageMetadata-Jbig2Parser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\Jbig2Parser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-Jbig2Parser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\Jbig2Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-Jbig2Parser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\Jpeg2000Parser",
            "name": "Jpeg2000Parser",
            "summary": "Parse\u0020JPEG\u00202000\u0020\u0028.jp2,\u0020.j2k,\u0020.j2c\u0029\u0020image\u0020headers.",
            "url": "classes/Phpdftk-ImageMetadata-Jpeg2000Parser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\Jpeg2000Parser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-Jpeg2000Parser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\Jpeg2000Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-Jpeg2000Parser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\JpegParser",
            "name": "JpegParser",
            "summary": "Parse\u0020JPEG\u0020headers\u0020\u0028SOF\u0020marker\u0029\u0020for\u0020dimensions,\u0020components,\u0020and\u0020color\u0020space.",
            "url": "classes/Phpdftk-ImageMetadata-JpegParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\JpegParser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-JpegParser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\JpegParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-JpegParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\PngParser",
            "name": "PngParser",
            "summary": "Parse\u0020PNG\u0020IHDR\u0020chunk\u0020for\u0020dimensions,\u0020bit\u0020depth,\u0020and\u0020color\u0020type.",
            "url": "classes/Phpdftk-ImageMetadata-PngParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\PngParser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-PngParser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\PngParser\u003A\u003AdecodeAlphaPng\u0028\u0029",
            "name": "decodeAlphaPng",
            "summary": "Decode\u0020an\u00208\u002Dbit\u0020alpha\u0020PNG\u0020\u0028color\u0020type\u00204\u0020\u003D\u0020grayscale\u002Balpha,\ntype\u00206\u0020\u003D\u0020RGB\u002Balpha\u0029\u0020into\u0020separate\u0020colour\u0020and\u0020alpha\u0020streams.",
            "url": "classes/Phpdftk-ImageMetadata-PngParser.html#method_decodeAlphaPng"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\PngParser\u003A\u003AdecodeIndexedPng\u0028\u0029",
            "name": "decodeIndexedPng",
            "summary": "Decode\u0020an\u00208\u002Dbit\u0020indexed\u002Dcolour\u0020PNG\u0020\u0028color\u0020type\u00203\u0029\u0020into\u0020the\nseparate\u0020colour\u0020\u002B\u0020alpha\u0020streams\u0020a\u0020PDF\u0020Image\u0020XObject\u0020embeds.",
            "url": "classes/Phpdftk-ImageMetadata-PngParser.html#method_decodeIndexedPng"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\PngParser\u003A\u003AextractIdatData\u0028\u0029",
            "name": "extractIdatData",
            "summary": "Extract\u0020the\u0020concatenated\u0020\u0060IDAT\u0060\u0020chunk\u0020payload\u0020from\u0020a\u0020PNG.",
            "url": "classes/Phpdftk-ImageMetadata-PngParser.html#method_extractIdatData"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\PngParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-PngParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\SvgParser",
            "name": "SvgParser",
            "summary": "Extract\u0020intrinsic\u002Dsize\u0020metadata\u0020from\u0020an\u0020SVG\u0020file\u0027s\u0020root\u0020\u0060\u003Csvg\u003E\u0060\nelement\u0020without\u0020parsing\u0020the\u0020full\u0020document\u0020tree.",
            "url": "classes/Phpdftk-ImageMetadata-SvgParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\SvgParser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-SvgParser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\SvgParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-SvgParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\TiffParser",
            "name": "TiffParser",
            "summary": "Parse\u0020TIFF\u0020IFD\u0020tags\u0020for\u0020dimensions,\u0020color\u0020space,\u0020and\u0020bit\u0020depth.",
            "url": "classes/Phpdftk-ImageMetadata-TiffParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\TiffParser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-TiffParser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\TiffParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-TiffParser.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\WebpParser",
            "name": "WebpParser",
            "summary": "Parse\u0020WebP\u0020container\u0020\u0028RIFF\/VP8\/VP8L\/VP8X\u0029\u0020for\u0020dimensions\u0020and\u0020alpha.",
            "url": "classes/Phpdftk-ImageMetadata-WebpParser.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\WebpParser\u003A\u003AparseFile\u0028\u0029",
            "name": "parseFile",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-WebpParser.html#method_parseFile"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata\\WebpParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-ImageMetadata-WebpParser.html#method_parse"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\ImageMetadata",
            "name": "ImageMetadata",
            "summary": "",
            "url": "namespaces/phpdftk-imagemetadata.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
