Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve",
            "name": "BezierCurve",
            "summary": "Cubic\u0020B\u00E9zier\u0020curve\u0020\u2014\u0020the\u0020primitive\u0020behind\u0020PDF\u0020path\u0020operators\u0020\u0028c,\u0020v,\u0020y\u0029.",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003ApointAt\u0028\u0029",
            "name": "pointAt",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#method_pointAt"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003Abounds\u0028\u0029",
            "name": "bounds",
            "summary": "Bounding\u0020box\u0020via\u0020extrema\u0020of\u0020the\u0020derivative\u0020polynomial",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#method_bounds"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003A\u0024p0",
            "name": "p0",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#property_p0"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003A\u0024p1",
            "name": "p1",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#property_p1"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003A\u0024p2",
            "name": "p2",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#property_p2"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\BezierCurve\u003A\u003A\u0024p3",
            "name": "p3",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-BezierCurve.html#property_p3"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix",
            "name": "Matrix",
            "summary": "Affine\u0020transformation\u0020matrix\u0020\u005Ba\u0020b\u0020c\u0020d\u0020e\u0020f\u005D.",
            "url": "classes/Phpdftk-Geometry-Matrix.html"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003Aidentity\u0028\u0029",
            "name": "identity",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_identity"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_toArray"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003Amultiply\u0028\u0029",
            "name": "multiply",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_multiply"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003Atranslate\u0028\u0029",
            "name": "translate",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_translate"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003Ascale\u0028\u0029",
            "name": "scale",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_scale"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003Arotate\u0028\u0029",
            "name": "rotate",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_rotate"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003AtransformPoint\u0028\u0029",
            "name": "transformPoint",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#method_transformPoint"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A\u0024a",
            "name": "a",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#property_a"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A\u0024b",
            "name": "b",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#property_b"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A\u0024c",
            "name": "c",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#property_c"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A\u0024d",
            "name": "d",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#property_d"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A\u0024e",
            "name": "e",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#property_e"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Matrix\u003A\u003A\u0024f",
            "name": "f",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Matrix.html#property_f"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize",
            "name": "PageSize",
            "summary": "Standard\u0020page\u0020dimensions\u0020as\u0020Rectangles\u0020in\u0020PDF\u0020points\u0020\u00281\/72\u0020inch\u0029.",
            "url": "classes/Phpdftk-Geometry-PageSize.html"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aletter\u0028\u0029",
            "name": "letter",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_letter"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Alegal\u0028\u0029",
            "name": "legal",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_legal"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Atabloid\u0028\u0029",
            "name": "tabloid",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_tabloid"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa0\u0028\u0029",
            "name": "a0",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a0"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa1\u0028\u0029",
            "name": "a1",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a1"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa2\u0028\u0029",
            "name": "a2",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a2"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa3\u0028\u0029",
            "name": "a3",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a3"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa4\u0028\u0029",
            "name": "a4",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a4"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa5\u0028\u0029",
            "name": "a5",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a5"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Aa6\u0028\u0029",
            "name": "a6",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_a6"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Ab4\u0028\u0029",
            "name": "b4",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_b4"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Ab5\u0028\u0029",
            "name": "b5",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_b5"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\PageSize\u003A\u003Alandscape\u0028\u0029",
            "name": "landscape",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-PageSize.html#method_landscape"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Point",
            "name": "Point",
            "summary": "2D\u0020point\u0020in\u0020PDF\u0020user\u002Dspace\u0020coordinates\u0020\u00281\u0020unit\u0020\u003D\u00201\/72\u0020inch\u0029.",
            "url": "classes/Phpdftk-Geometry-Point.html"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Point\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Point.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Point\u003A\u003A\u0024x",
            "name": "x",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Point.html#property_x"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Point\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Point.html#property_y"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle",
            "name": "Rectangle",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method_toArray"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003Acontains\u0028\u0029",
            "name": "contains",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method_contains"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003Aintersect\u0028\u0029",
            "name": "intersect",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method_intersect"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method_union"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003Ascale\u0028\u0029",
            "name": "scale",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method_scale"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#method_expand"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003A\u0024x",
            "name": "x",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#property_x"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#property_y"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#property_width"
        },                {
            "fqsen": "\\Phpdftk\\Geometry\\Rectangle\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/Phpdftk-Geometry-Rectangle.html#property_height"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Geometry",
            "name": "Geometry",
            "summary": "",
            "url": "namespaces/phpdftk-geometry.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
