Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor",
            "name": "CmykColor",
            "summary": "CMYK\u0020color\u0020with\u0020components\u0020in\u00200.0\u20131.0\u0020range\u0020\u2014\u0020maps\u0020to\u0020PDF\u0020DeviceCMYK.",
            "url": "classes/Phpdftk-Color-CmykColor.html"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003AtoRgb\u0028\u0029",
            "name": "toRgb",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#method_toRgb"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#method_toArray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003AgetColorSpace\u0028\u0029",
            "name": "getColorSpace",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#method_getColorSpace"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003A\u0024c",
            "name": "c",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#property_c"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003A\u0024m",
            "name": "m",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#property_m"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#property_y"
        },                {
            "fqsen": "\\Phpdftk\\Color\\CmykColor\u003A\u003A\u0024k",
            "name": "k",
            "summary": "",
            "url": "classes/Phpdftk-Color-CmykColor.html#property_k"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorConverter",
            "name": "ColorConverter",
            "summary": "Lossless\u0020color\u0020model\u0020conversions\u0020between\u0020RGB,\u0020CMYK,\u0020and\u0020Gray.",
            "url": "classes/Phpdftk-Color-ColorConverter.html"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorConverter\u003A\u003ArgbToCmyk\u0028\u0029",
            "name": "rgbToCmyk",
            "summary": "",
            "url": "classes/Phpdftk-Color-ColorConverter.html#method_rgbToCmyk"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorConverter\u003A\u003AcmykToRgb\u0028\u0029",
            "name": "cmykToRgb",
            "summary": "",
            "url": "classes/Phpdftk-Color-ColorConverter.html#method_cmykToRgb"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorConverter\u003A\u003ArgbToGray\u0028\u0029",
            "name": "rgbToGray",
            "summary": "",
            "url": "classes/Phpdftk-Color-ColorConverter.html#method_rgbToGray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorConverter\u003A\u003AgrayToRgb\u0028\u0029",
            "name": "grayToRgb",
            "summary": "",
            "url": "classes/Phpdftk-Color-ColorConverter.html#method_grayToRgb"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorInterface",
            "name": "ColorInterface",
            "summary": "Common\u0020contract\u0020for\u0020PDF\u0020color\u0020operands\u0020\u2014\u0020used\u0020by\u0020ContentStream\u0020color\u0020operators.",
            "url": "classes/Phpdftk-Color-ColorInterface.html"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Phpdftk-Color-ColorInterface.html#method_toArray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\ColorInterface\u003A\u003AgetColorSpace\u0028\u0029",
            "name": "getColorSpace",
            "summary": "",
            "url": "classes/Phpdftk-Color-ColorInterface.html#method_getColorSpace"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor",
            "name": "GrayColor",
            "summary": "Grayscale\u0020color\u0020\u00280.0\u0020\u003D\u0020black,\u00201.0\u0020\u003D\u0020white\u0029\u0020\u2014\u0020maps\u0020to\u0020PDF\u0020DeviceGray.",
            "url": "classes/Phpdftk-Color-GrayColor.html"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003Ablack\u0028\u0029",
            "name": "black",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#method_black"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003Awhite\u0028\u0029",
            "name": "white",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#method_white"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003AtoRgb\u0028\u0029",
            "name": "toRgb",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#method_toRgb"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#method_toArray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003AgetColorSpace\u0028\u0029",
            "name": "getColorSpace",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#method_getColorSpace"
        },                {
            "fqsen": "\\Phpdftk\\Color\\GrayColor\u003A\u003A\u0024gray",
            "name": "gray",
            "summary": "",
            "url": "classes/Phpdftk-Color-GrayColor.html#property_gray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor",
            "name": "RgbColor",
            "summary": "RGB\u0020color\u0020with\u0020components\u0020in\u00200.0\u20131.0\u0020range\u0020\u2014\u0020maps\u0020to\u0020PDF\u0020DeviceRGB.",
            "url": "classes/Phpdftk-Color-RgbColor.html"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003AfromInt\u0028\u0029",
            "name": "fromInt",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method_fromInt"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003AfromHex\u0028\u0029",
            "name": "fromHex",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method_fromHex"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003AtoCmyk\u0028\u0029",
            "name": "toCmyk",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method_toCmyk"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003AtoGray\u0028\u0029",
            "name": "toGray",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method_toGray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method_toArray"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003AgetColorSpace\u0028\u0029",
            "name": "getColorSpace",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#method_getColorSpace"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003A\u0024r",
            "name": "r",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#property_r"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003A\u0024g",
            "name": "g",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#property_g"
        },                {
            "fqsen": "\\Phpdftk\\Color\\RgbColor\u003A\u003A\u0024b",
            "name": "b",
            "summary": "",
            "url": "classes/Phpdftk-Color-RgbColor.html#property_b"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Color",
            "name": "Color",
            "summary": "",
            "url": "namespaces/phpdftk-color.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
