Search.appendIndex(
    [
                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpPacket",
            "name": "XmpPacket",
            "summary": "Immutable\u0020bag\u0020of\u0020XMP\u0020metadata\u0020properties.",
            "url": "classes/Phpdftk-Xmp-XmpPacket.html"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpPacket\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpPacket.html#method_create"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpPacket\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpPacket.html#method_get"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpPacket\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpPacket.html#method_set"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpPacket\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpPacket.html#method_has"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpPacket\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpPacket.html#method_all"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpReader",
            "name": "XmpReader",
            "summary": "Parse\u0020XMP\u0020metadata\u0020packets\u0020from\u0020XML\u0020into\u0020\u007B\u0040see\u0020XmpPacket\u007D.",
            "url": "classes/Phpdftk-Xmp-XmpReader.html"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpReader\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpReader.html#method_parse"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpWriter",
            "name": "XmpWriter",
            "summary": "Serialize\u0020an\u0020\u007B\u0040see\u0020XmpPacket\u007D\u0020into\u0020an\u0020XMP\u0020XML\u0020packet\u0020with\u0020\u0060\u003C\u003Fxpacket\u003F\u003E\u0060\u0020wrapping.",
            "url": "classes/Phpdftk-Xmp-XmpWriter.html"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpWriter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpWriter.html#method___construct"
        },                {
            "fqsen": "\\Phpdftk\\Xmp\\XmpWriter\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Phpdftk-Xmp-XmpWriter.html#method_serialize"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Phpdftk\\Xmp",
            "name": "Xmp",
            "summary": "",
            "url": "namespaces/phpdftk-xmp.html"
        },                {
            "fqsen": "\\Phpdftk",
            "name": "Phpdftk",
            "summary": "",
            "url": "namespaces/phpdftk.html"
        }            ]
);
