<?php

declare(strict_types=1);

namespace Phpdftk\Pdf\Reader\Tests\Integration;

use Phpdftk\Pdf\Core\PdfArray;
use Phpdftk\Pdf\Core\PdfDictionary;
use Phpdftk\Pdf\Core\PdfName;
use Phpdftk\Pdf\Core\PdfReference;
use Phpdftk\Pdf\Core\PdfString;
use Phpdftk\Pdf\Reader\PdfReader;
use PHPUnit\Framework\TestCase;

/**
 * Read each sample PDF generated by the writer tests and verify
 * structural properties: page count, catalog type, font references,
 * annotation presence, etc.
 */
class ReadSamplePdfsTest extends TestCase
{
    private const SAMPLES_DIR = __DIR__ . '/../../../../../docs/sample-pdfs';

    private function samplePath(string $name): string
    {
        $path = self::SAMPLES_DIR . '/' . $name;
        if (!file_exists($path)) {
            self::markTestSkipped("Sample PDF not found: $name — run the writer tests first");
        }
        return $path;
    }

    public function testSimpleText(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('simple_text.pdf'));
        self::assertSame('1.7', $pdf->getVersion());
        self::assertSame(3, $pdf->getPageCount());

        $catalog = $pdf->getCatalog();
        $type = $catalog->get('Type');
        self::assertInstanceOf(PdfName::class, $type);
        self::assertSame('Catalog', $type->value);

        $pages = $pdf->getPages();
        self::assertCount(3, $pages);
        foreach ($pages as $page) {
            self::assertTrue($page->has('MediaBox'));
        }
    }

    public function testAnnotations(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('annotations.pdf'));
        $pages = $pdf->getPages();
        // At least one page should have annotations
        $hasAnnots = false;
        foreach ($pages as $page) {
            if ($page->has('Annots')) {
                $hasAnnots = true;
                break;
            }
        }
        self::assertTrue($hasAnnots, 'Expected at least one page with /Annots');
    }

    public function testBookmarks(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('bookmarks.pdf'));
        $catalog = $pdf->getCatalog();
        self::assertTrue($catalog->has('Outlines'), 'Catalog should have /Outlines');
    }

    public function testFormFields(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('form_fields.pdf'));
        $catalog = $pdf->getCatalog();
        self::assertTrue($catalog->has('AcroForm'), 'Catalog should have /AcroForm');
    }

    public function testMultiPageComplex(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('multi_page_complex.pdf'));
        self::assertSame(10, $pdf->getPageCount());
        $info = $pdf->getInfo();
        self::assertNotNull($info);
        self::assertTrue($info->has('Title'));
    }

    public function testEmbeddedFonts(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('embedded_fonts.pdf'));
        $pages = $pdf->getPages();
        self::assertGreaterThan(0, count($pages));
    }

    public function testPageLabels(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('page_labels.pdf'));
        $catalog = $pdf->getCatalog();
        self::assertTrue($catalog->has('PageLabels'), 'Catalog should have /PageLabels');
    }

    public function testGraphics(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('graphics.pdf'));
        self::assertGreaterThan(0, $pdf->getPageCount());
    }

    public function testDocumentFeatures(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('document_features.pdf'));
        $catalog = $pdf->getCatalog();
        self::assertTrue($catalog->has('StructTreeRoot') || $catalog->has('Names'));
    }

    public function testFromString(): void
    {
        $bytes = file_get_contents($this->samplePath('simple_text.pdf'));
        self::assertNotFalse($bytes);
        $pdf = PdfReader::fromString($bytes);
        self::assertSame(3, $pdf->getPageCount());
    }

    public function testFromStream(): void
    {
        $stream = fopen($this->samplePath('simple_text.pdf'), 'rb');
        self::assertIsResource($stream);
        $pdf = PdfReader::fromStream($stream);
        fclose($stream);
        self::assertSame(3, $pdf->getPageCount());
    }

    public function testXrefStream(): void
    {
        $pdf = PdfReader::fromFile($this->samplePath('xref_stream.pdf'));
        self::assertSame('1.5', $pdf->getVersion());
        self::assertSame(1, $pdf->getPageCount());
        $catalog = $pdf->getCatalog();
        $type = $catalog->get('Type');
        self::assertInstanceOf(PdfName::class, $type);
        self::assertSame('Catalog', $type->value);
    }

    public function testMarkupAnnotations(): void
    {
        $path = self::SAMPLES_DIR . '/markup_annotations.pdf';
        if (!file_exists($path)) {
            self::markTestSkipped('markup_annotations.pdf not found');
        }
        $pdf = PdfReader::fromFile($path);
        self::assertGreaterThan(0, $pdf->getPageCount());
    }

    public function testHighLevelPdf(): void
    {
        $path = self::SAMPLES_DIR . '/high_level_pdf.pdf';
        if (!file_exists($path)) {
            self::markTestSkipped('high_level_pdf.pdf not found');
        }
        $pdf = PdfReader::fromFile($path);
        self::assertGreaterThanOrEqual(3, $pdf->getPageCount());
    }

    public function testIsLinearizedReturnsFalseForNormalPdf(): void
    {
        $writer = new \Phpdftk\Pdf\Writer\PdfWriter(compressStreams: false);
        $writer->addPage(612, 792);
        $bytes = $writer->generate();

        $pdf = PdfReader::fromString($bytes);
        self::assertFalse($pdf->isLinearized());
        self::assertNull($pdf->getLinearizationParameters());
    }

    public function testIsLinearizedReturnsTrueForLinearizedPdf(): void
    {
        // Build a minimal PDF with a linearization dict as object 1
        $writer = new \Phpdftk\Pdf\Core\File\PdfFileWriter(compressStreams: false);

        // Register linearization dict first (object 1)
        $linDict = new \Phpdftk\Pdf\Core\Document\LinearizationParameters();
        $linDict->n = 1;
        $linDict->l = 0; // will be wrong but that's fine for detection
        $writer->register($linDict);

        $catalog = new \Phpdftk\Pdf\Core\Document\Catalog();
        $writer->setCatalog($catalog);

        $pageTree = new \Phpdftk\Pdf\Core\Document\PageTree();
        $writer->register($pageTree);
        $catalog->pages = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);

        $page = new \Phpdftk\Pdf\Core\Document\Page();
        $writer->register($page);
        $page->parent = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page->mediaBox = new \Phpdftk\Pdf\Core\PdfArray([
            new \Phpdftk\Pdf\Core\PdfNumber(0), new \Phpdftk\Pdf\Core\PdfNumber(0),
            new \Phpdftk\Pdf\Core\PdfNumber(612), new \Phpdftk\Pdf\Core\PdfNumber(792),
        ]);
        $pageTree->kids = [new \Phpdftk\Pdf\Core\PdfReference($page->objectNumber)];
        $pageTree->count = 1;

        $bytes = $writer->generate();

        $pdf = PdfReader::fromString($bytes);
        self::assertTrue($pdf->isLinearized());

        $params = $pdf->getLinearizationParameters();
        self::assertNotNull($params);
        self::assertSame(1.0, $params['linearized']);
        self::assertSame(1, $params['pageCount']);
    }

    public function testGetPageOffsetHintTableReturnsNullForNonLinearized(): void
    {
        $writer = new \Phpdftk\Pdf\Core\File\PdfFileWriter(compressStreams: false);
        $catalog = new \Phpdftk\Pdf\Core\Document\Catalog();
        $writer->setCatalog($catalog);
        $pageTree = new \Phpdftk\Pdf\Core\Document\PageTree();
        $writer->register($pageTree);
        $catalog->pages = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page = new \Phpdftk\Pdf\Core\Document\Page();
        $writer->register($page);
        $page->parent = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page->mediaBox = new \Phpdftk\Pdf\Core\PdfArray([
            new \Phpdftk\Pdf\Core\PdfNumber(0), new \Phpdftk\Pdf\Core\PdfNumber(0),
            new \Phpdftk\Pdf\Core\PdfNumber(612), new \Phpdftk\Pdf\Core\PdfNumber(792),
        ]);
        $pageTree->kids = [new \Phpdftk\Pdf\Core\PdfReference($page->objectNumber)];
        $pageTree->count = 1;

        $pdf = PdfReader::fromString($writer->generate());
        self::assertNull($pdf->getPageOffsetHintTable());
    }

    public function testGetPageOffsetHintTableReturnsNullWhenHArrayMissing(): void
    {
        // Build a "linearized-looking" PDF without a /H array → should return null.
        $writer = new \Phpdftk\Pdf\Core\File\PdfFileWriter(compressStreams: false);
        $linDict = new \Phpdftk\Pdf\Core\Document\LinearizationParameters();
        $linDict->n = 1;
        $linDict->l = 1000;
        $writer->register($linDict);

        $catalog = new \Phpdftk\Pdf\Core\Document\Catalog();
        $writer->setCatalog($catalog);
        $pageTree = new \Phpdftk\Pdf\Core\Document\PageTree();
        $writer->register($pageTree);
        $catalog->pages = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page = new \Phpdftk\Pdf\Core\Document\Page();
        $writer->register($page);
        $page->parent = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page->mediaBox = new \Phpdftk\Pdf\Core\PdfArray([
            new \Phpdftk\Pdf\Core\PdfNumber(0), new \Phpdftk\Pdf\Core\PdfNumber(0),
            new \Phpdftk\Pdf\Core\PdfNumber(612), new \Phpdftk\Pdf\Core\PdfNumber(792),
        ]);
        $pageTree->kids = [new \Phpdftk\Pdf\Core\PdfReference($page->objectNumber)];
        $pageTree->count = 1;

        $pdf = PdfReader::fromString($writer->generate());
        // Linearized but no /H array data → hint table parsing returns null
        self::assertNull($pdf->getPageOffsetHintTable());
    }

    public function testGetPageByteRangeReturnsNullForNonLinearizedPdf(): void
    {
        $writer = new \Phpdftk\Pdf\Core\File\PdfFileWriter(compressStreams: false);
        $catalog = new \Phpdftk\Pdf\Core\Document\Catalog();
        $writer->setCatalog($catalog);
        $pageTree = new \Phpdftk\Pdf\Core\Document\PageTree();
        $writer->register($pageTree);
        $catalog->pages = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page = new \Phpdftk\Pdf\Core\Document\Page();
        $writer->register($page);
        $page->parent = new \Phpdftk\Pdf\Core\PdfReference($pageTree->objectNumber);
        $page->mediaBox = new \Phpdftk\Pdf\Core\PdfArray([
            new \Phpdftk\Pdf\Core\PdfNumber(0), new \Phpdftk\Pdf\Core\PdfNumber(0),
            new \Phpdftk\Pdf\Core\PdfNumber(612), new \Phpdftk\Pdf\Core\PdfNumber(792),
        ]);
        $pageTree->kids = [new \Phpdftk\Pdf\Core\PdfReference($page->objectNumber)];
        $pageTree->count = 1;

        $pdf = PdfReader::fromString($writer->generate());
        self::assertNull($pdf->getPageByteRange(0));
    }
}
