<?php

declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';

chdir(__DIR__);

// Setup: build a small form PDF with text + checkbox + combo box.
// (In real usage this would already exist — generated by a designer or
// an upstream system.)
{
    $writer = new Phpdftk\Pdf\Writer\PdfWriter(compressStreams: false);
    $page = $writer->addPage(612, 792);
    $writer->addFont(new Phpdftk\Pdf\Core\Font\Type1Font(Phpdftk\Pdf\Core\Font\StandardFont::Helvetica));

    $cs = $writer->addContentStream($page);
    $cs->beginText()->setFont('F1', 14)->moveTextPosition(72, 740)->showText('Subscriber Sign-Up')->endText();
    foreach ([['Name:', 690], ['Email:', 645], ['Country:', 600], ['Subscribe?', 545]] as [$label, $y]) {
        $cs->beginText()->setFont('F1', 11)->moveTextPosition(72, $y)->showText($label)->endText();
    }

    $register = function (string $klass, string $name, array $extras = []) use ($writer, $page) {
        $field = new $klass();
        $field->t = new Phpdftk\Pdf\Core\PdfString($name);
        $field->da = new Phpdftk\Pdf\Core\PdfString('/F1 12 Tf 0 g');
        foreach ($extras as $k => $v) {
            $field->{$k} = $v;
        }
        $writer->register($field);
        return $field;
    };
    $attach = function ($field, array $rect) use ($writer, $page) {
        $widget = new Phpdftk\Pdf\Core\Annotation\WidgetAnnotation(new Phpdftk\Pdf\Core\PdfArray(array_map(fn($n) => new Phpdftk\Pdf\Core\PdfNumber($n), $rect)));
        $widget->parent = new Phpdftk\Pdf\Core\PdfReference($field->objectNumber);
        $writer->register($widget);
        $field->kids = [new Phpdftk\Pdf\Core\PdfReference($widget->objectNumber)];
        $page->corePage()->annots[] = new Phpdftk\Pdf\Core\PdfReference($widget->objectNumber);
    };

    $name = $register(Phpdftk\Pdf\Core\Interactive\Form\TextField::class, 'name');
    $attach($name, [150, 685, 400, 705]);
    $email = $register(Phpdftk\Pdf\Core\Interactive\Form\TextField::class, 'email', ['maxLen' => 50]);
    $attach($email, [150, 640, 400, 660]);
    $country = $register(Phpdftk\Pdf\Core\Interactive\Form\ChoiceField::class, 'country', [
        'ff' => 1 << 17,
        'opt' => new Phpdftk\Pdf\Core\PdfArray([
            new Phpdftk\Pdf\Core\PdfString('United States'),
            new Phpdftk\Pdf\Core\PdfString('Canada'),
            new Phpdftk\Pdf\Core\PdfString('United Kingdom'),
        ]),
    ]);
    $attach($country, [150, 595, 400, 615]);
    $subscribe = $register(Phpdftk\Pdf\Core\Interactive\Form\ButtonField::class, 'subscribe', ['ff' => 0]);
    $attach($subscribe, [150, 540, 165, 555]);

    $acroForm = new Phpdftk\Pdf\Core\Interactive\Form\AcroForm();
    $acroForm->fields = array_map(
        fn($f) => new Phpdftk\Pdf\Core\PdfReference($f->objectNumber),
        [$name, $email, $country, $subscribe],
    );
    $acroForm->needAppearances = true;
    $acroForm->da = new Phpdftk\Pdf\Core\PdfString('/F1 12 Tf 0 g');
    $writer->register($acroForm);
    $writer->getCatalog()->acroForm = new Phpdftk\Pdf\Core\PdfReference($acroForm->objectNumber);

    file_put_contents('blank-form.pdf', $writer->generate());
}

// region: example
use Phpdftk\Pdf\Toolkit\FormFiller;

$filled = FormFiller::open('blank-form.pdf')
    ->fill('name', 'Jane Doe')
    ->fill('email', 'jane@example.com')
    ->select('country', 'Canada')
    ->check('subscribe', true)
    ->toBytes();

file_put_contents('signup.pdf', $filled);

// Inspect what a downstream consumer would see:
foreach (FormFiller::openString($filled)->getFieldNames() as $name) {
    echo $name . "\n";
}
// endregion

rename(__DIR__ . '/blank-form.pdf', example_output_path('toolkit/form-filler/input.pdf'));
rename(__DIR__ . '/signup.pdf', example_output_path('toolkit/form-filler/output.pdf'));
